// Get Bot Session (PREMIUM) -- the live cycle-semantics gate, with ONE line removed.
//
// GENERATED by scripts/build-premium-concierge.mjs from the live Get Bot Session node.
// Do not edit here. This is the live code minus the /start reset, and nothing else.
//
// REMOVED:  if (isStart) reset = 'start';
//
// In the premium flow, /start after a committed submission must land on the terminal screen
// with the lead intact. Minting a new cycle here would destroy the lead before the state
// machine ever saw it, and the terminal rule would be enforcing nothing.
//
// isRestart and hasNoCycle are UNCHANGED: a session with no cycle still bootstraps one, and
// the legacy m|diag restart stays as it is -- the premium flow never sends that callback, so
// it is inert here rather than removed.
// CYCLE SEMANTICS GATE (P0 fix for stale consent).
// Every consumer that reads $('Get Bot Session') now sees a CYCLE-VALID view of the session:
// consent and lead_id from a previous application cycle are invalidated before the state machine ever sees them.
// A new cycle is created ONLY on an explicit reset: /start, or "Начать заново" (m|diag pressed on a session that
// already carries a consent decision, a lead, or an ended session). Plain navigation (/menu, n|menu) never changes it.
// An unfinished diagnostic cycle is never reset by m|diag, because there the same callback means "continue".
const p = $('Parse Telegram Update').first().json;
const rows = $input.all().map(i => i.json).filter(r => r && String(r.chat_id == null ? '' : r.chat_id).trim() !== '');
const s = Object.assign({}, rows.length ? rows[0] : {});
const now = new Date().toISOString();
const text = String(p.message_text || '').trim().toLowerCase();
const cb = String(p.callback_data || '').trim();
const str = v => String(v == null ? '' : v).trim();
// ============ B.2.1-C P7.2 — ISSUANCE INPUTS, CAPTURED BEFORE THIS GATE MUTATES s ============
const persistedSubmissionKey = str(s.submission_key);
const persistedCycleIdAtEntry = str(s.cycle_id);

const isStart = text === '/start';
// "Завершённый" цикл: есть решение по согласию, есть лид, либо сессия явно завершена кнопкой "Завершить".
const carriesFinishedCycle = str(s.consent) !== '' || str(s.lead_id) !== '' || str(s.status).toLowerCase() === 'ended';
const isRestart = cb === 'm|diag' && carriesFinishedCycle;
const hasNoCycle = str(s.cycle_id) === '';

let cycleId = str(s.cycle_id);
let reset = '';
// [premium] REMOVED: /start no longer resets the cycle. `if (false)` rather than a comment,
// because this line heads an if/else chain and commenting it out orphans the `else` below.
if (false) { reset = 'start'; }
else if (isRestart) reset = 'restart';
else if (hasNoCycle) reset = 'bootstrap';
if (reset) cycleId = 'C-' + str(p.chat_id) + '-' + Date.now();

function archiveLead() {
  const old = str(s.lead_id);
  if (old) {
    const prev = str(s.previous_lead_id).split(';').map(x => x.trim()).filter(Boolean);
    if (!prev.includes(old)) prev.push(old);
    s.previous_lead_id = prev.join('; ').slice(0, 500);
  }
  s.lead_id = ''; s.lead_cycle_id = ''; s.lead_sent_at = ''; s.lead_intake_ok = '';
}

if (reset === 'start' || reset === 'restart') {
  // Explicit reset: a genuinely new application cycle.
  s.consent = ''; s.consent_cycle_id = ''; s.consent_at = '';
  archiveLead();
  s.selected_service = ''; s.business_model = ''; s.turnover_range = ''; s.main_pain = '';
  s.urgency = ''; s.has_cfo = ''; s.documents_status = ''; s.free_text_request = '';
  s.raw_json = ''; s.status = 'active'; s.state = 'MENU'; s.notes = '';
  // Identity and contact convenience fields are deliberately kept; on their own they cannot submit anything,
  // because consent is now empty and lead_ready requires a current-cycle consent.
}

s.cycle_id = cycleId;

// Independent of any reset: never let a consent or a lead from another cycle count for this one.
if (str(s.consent) !== '' && str(s.consent_cycle_id) !== cycleId) { s.consent = ''; s.consent_cycle_id = ''; s.consent_at = ''; }
if (str(s.lead_id) !== '' && str(s.lead_cycle_id) !== cycleId) { archiveLead(); }

s.cycle_reset = reset;

// ================ B.2.1-C P7.2 — SUBMISSION KEY ISSUANCE (ISSUANCE_ORDER step 1) ================
//
// The deployed form of decideIssuance() in n8n/src/concierge-issuer/mint-submission-key.js.
// The module is the GATED statement of this logic; qa/concierge-issuer-candidate.test.mjs
// drives both against one table of cases, so the two cannot drift apart silently.
//
// THE PRIMITIVE. require('crypto').randomBytes is the ONLY entropy source that answers in this
// sandbox: execution 3651 measured "typeof crypto === undefined" on this tenant. Writing the
// modern reflex (crypto.getRandomValues) or the specification's literal (crypto.randomBytes)
// here is not a degraded feature — it is a ReferenceError inside the node that every Telegram
// update passes through, i.e. a bot that stops answering /start for every user.
//
// THE FAILURE POSTURE. The mint is wrapped, and that wrapper is load-bearing. This node runs
// BEFORE the reply is composed, so an exception here costs the user their message. A mint that
// throws degrades to MINT_FAILED: the turn still answers, and it is the GRAPH that refuses to
// persist the new cycle. planIssuance() is explicit about why that refusal is the safe half — a
// half-advanced authority row (new cycle_id, no submission_key) makes every submit
// PRE_ACTIVATION_BLOCKED, locking the user out of a cycle that looks current.
//
// NEVER_BACKFILL. A cycle that exists without a key is NEVER given one retroactively. A legacy
// cycle may already have submitted — lead_id set, CRM row written — and a fresh READY receipt is
// positive evidence to the gateway that it has NOT, releasing a second attempt for a lead that
// is already in the pipeline. Cost of refusing: one restart. Cost of backfilling: a duplicate
// lead.
//
// The four annotations below are __-prefixed on purpose. They are decision metadata, not sheet
// columns, and F16 proved that a stray property reaching Save Bot Session does not vanish — it
// permanently widens Bot_Sessions. The three row builders emit their declared COLS only, and the
// prefix makes it visible at a glance that these were never candidates for that list.
const SUBMISSION_KEY_RE = /^sub_[0-9a-f]{32}$/;
function mintSubmissionKey() {
  const buf = require('crypto').randomBytes(16);
  if (!buf || typeof buf.length !== 'number' || buf.length !== 16) { throw new Error('randomBytes did not return 16 bytes'); }
  let hex = '';
  for (let i = 0; i < 16; i++) {
    const b = buf[i];
    if (typeof b !== 'number' || !isFinite(b) || b < 0 || b > 255 || (b | 0) !== b) { throw new Error('randomBytes returned a non-byte at index ' + i); }
    hex += (b < 16 ? '0' : '') + b.toString(16);
  }
  const k = 'sub_' + hex;
  if (!SUBMISSION_KEY_RE.test(k)) { throw new Error('minted key failed the format rule'); }
  return k;
}

let keyAction = '';
let keyReason = '';
let keyPreallocate = false;
if (reset !== '') {
  // A key is minted IF AND ONLY IF a new cycle is minted. Anything else desynchronises the pair
  // Bot_Sessions carries, and the gateway's SUBMISSION_KEY_DRIFT check exists precisely because
  // that pair must move together or not at all.
  try {
    s.submission_key = mintSubmissionKey();
    keyAction = 'MINT';
    keyReason = 'NEW_CYCLE_' + reset.toUpperCase();
    keyPreallocate = true;
  } catch (e) {
    s.submission_key = '';
    keyAction = 'MINT_FAILED';
    keyReason = 'MINT_THREW:' + String((e && e.message) || e).slice(0, 120);
  }
} else if (SUBMISSION_KEY_RE.test(persistedSubmissionKey)) {
  s.submission_key = persistedSubmissionKey;
  keyAction = 'CARRY';
  keyReason = 'CYCLE_UNCHANGED';
} else if (persistedSubmissionKey !== '') {
  // Carried UNCHANGED and never repaired. The gateway already refuses a malformed key
  // (SUBMISSION_KEY_INVALID, proven live); blanking it here would destroy the only evidence
  // that the row is corrupt while producing the identical refusal. The issuer reports; it does
  // not launder.
  s.submission_key = persistedSubmissionKey;
  keyAction = 'CARRY_MALFORMED';
  keyReason = 'KEY_MALFORMED_NOT_REPAIRED';
} else {
  s.submission_key = '';
  keyAction = 'LEGACY_NO_KEY';
  keyReason = persistedCycleIdAtEntry !== '' ? 'LEGACY_CYCLE_NOT_BACKFILLED' : 'NO_CYCLE_NO_KEY';
}
s.__submission_key_action = keyAction;
s.__submission_key_reason = keyReason;
s.__submission_key_preallocate = keyPreallocate;
s.__submission_key_fault = keyAction === 'MINT_FAILED';
return [{ json: s }];