-- ============================================================================
-- FINMENTOR NEW LEAD ALERT OUTBOX - forward migration (doc sections 4.1-4.7)
-- SOURCE OF TRUTH: docs/NEW_LEAD_ALERT_OUTBOX_DDL_REVIEW.md
-- This file is a VERBATIM materialisation of the SQL fences in that document.
-- Generated by db/validation/extract-migration.mjs -- do not hand-edit.
-- ============================================================================
-- ============================================================================
-- FINMENTOR — NEW LEAD ALERT OUTBOX          forward migration, v2
-- PRECONDITION: see §8. Do not run without owner approval.
-- ============================================================================
BEGIN;

-- ------------------------------------------------------------------- roles
-- All NOLOGIN. Group roles only: a later, dedicated DB login may be GRANTed one of
-- these. It must NOT be, and is not here, any G5 role or credential.
DO $$
DECLARE r text;
BEGIN
  FOREACH r IN ARRAY ARRAY['alerts_owner','alerts_writer','alerts_dispatcher',
                           'alerts_reconciler','alerts_retention','alerts_audit'] LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
      EXECUTE format('CREATE ROLE %I NOLOGIN NOBYPASSRLS NOINHERIT', r);
    END IF;
  END LOOP;
END $$;

-- alerts_owner OWNS every object below. It is deliberately NOBYPASSRLS: the RLS exemption
-- in §4.7 comes from OWNERSHIP, not from a bypass attribute, so revoking ownership revokes
-- the exemption with it.
COMMENT ON ROLE alerts_owner IS
  'NOLOGIN. Owns the alerts schema, its tables, views and SECURITY DEFINER functions. '
  'Never granted to a runtime role. Never granted to, and never a member of, any G5 role.';

-- The migrator must be a member of alerts_owner to hand ownership over. This membership is
-- what future migrations will also need; it is granted explicitly rather than acquired by
-- accident, and it is listed in §11 so it is visible in every audit.
--
-- AMENDMENT 2.1-A (real-Postgres proof, §16). The grant is UNCONDITIONAL and deliberately so.
-- PostgreSQL 16+ automatically records a membership when a CREATEROLE migrator creates a role,
-- and that automatic grant carries admin_option = true but inherit_option = false and
-- set_option = false. pg_has_role(..., 'MEMBER') is TRUE for it, so a guard on 'MEMBER' skipped
-- the real grant -- and assigning ownership needs SET, which the automatic grant does not give.
-- The next statement then failed with 42501 "must be able to SET ROLE alerts_owner" for every
-- non-superuser migrator, which is exactly the Supabase `postgres` shape.
--
-- AMENDMENT 2.2-A (real-Postgres proof). The OPTIONS ARE NOW NAMED, and that is not decoration.
-- §4.7 hands the working membership back before COMMIT, so on every run after the first the
-- membership row already exists with set_option = false. A bare `GRANT role TO member` does NOT
-- update an existing membership -- PostgreSQL answers NOTICE "is already a member of role" and
-- changes nothing -- so the reapply, the rollback and the reapply-after-rollback ALL failed with
-- 42501 again until the options were spelled out. Named options update an existing grant.
-- INHERIT is needed for the privileges (DROP OWNED BY, and the schema drops in §5); SET is needed
-- to assign ownership. Both are revoked again in §4.7.
DO $$ BEGIN
  EXECUTE format('GRANT alerts_owner TO %I WITH INHERIT TRUE', current_user);
  EXECUTE format('GRANT alerts_owner TO %I WITH SET TRUE',     current_user);
END $$;

CREATE SCHEMA IF NOT EXISTS alerts AUTHORIZATION alerts_owner;
ALTER SCHEMA alerts OWNER TO alerts_owner;
COMMENT ON SCHEMA alerts IS
  'FINMENTOR notification outbox. Independent of public.telegram_initdata_replays (G5): no role '
  'granted here may read or write the G5 replay ledger, and no G5 role is granted anything here. '
  'No runtime role holds a table privilege in this schema — access is by EXECUTE only.';

-- The ONLY place a request fingerprint is computed. IMMUTABLE and STRICT so it is a pure
-- function of its input; PARALLEL SAFE because it touches nothing. Deliberately NOT granted
-- to any runtime role: the functions that need it are SECURITY DEFINER and run as the owner,
-- so exposing it would only create a hashing oracle with no operational purpose.
CREATE OR REPLACE FUNCTION alerts.request_fingerprint(p_request_id text)
RETURNS text
LANGUAGE sql
IMMUTABLE STRICT PARALLEL SAFE
SET search_path = pg_catalog
AS $fn$
  SELECT encode(
           sha256(convert_to('finmentor:new_lead:v1:' || p_request_id, 'UTF8')),
           'hex')
$fn$;
ALTER FUNCTION alerts.request_fingerprint(text) OWNER TO alerts_owner;
COMMENT ON FUNCTION alerts.request_fingerprint(text) IS
  'SHA-256 over a domain-separated canonical request id. PSEUDONYMISATION / DATA MINIMISATION, '
  'NOT anonymisation: the derivation is public and unkeyed, so a party already holding a '
  'candidate identifier can confirm it. See docs 2.4. v2 (HMAC with an out-of-table pepper) '
  'is the recorded upgrade path and is NOT implemented.';

-- ---------------------------------------------------------------- the event
CREATE TABLE IF NOT EXISTS alerts.new_lead_outbox (
  -- The durable identity. THE RAW request_id IS NOT STORED — not here, not anywhere in alerts.*.
  request_fingerprint text     NOT NULL,
  fingerprint_version smallint NOT NULL DEFAULT 1,
  -- Derived, never supplied: the caller cannot choose the key, and the key cannot disagree
  -- with the fingerprint.
  dispatch_key    text GENERATED ALWAYS AS ('NEW_LEAD:' || request_fingerprint) STORED,

  event_type      text        NOT NULL DEFAULT 'NEW_LEAD',
  request_route   text        NOT NULL,
  lead_id         text        NOT NULL,
  schema_version  smallint    NOT NULL DEFAULT 1,
  settled_at      timestamptz NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  payload_json    jsonb       NOT NULL,
  payload_purged_at timestamptz,

  CONSTRAINT new_lead_outbox_pk PRIMARY KEY (dispatch_key),
  CONSTRAINT new_lead_outbox_fingerprint_uk UNIQUE (request_fingerprint),

  CONSTRAINT new_lead_outbox_fingerprint_ck CHECK (request_fingerprint ~ '^[0-9a-f]{64}$'),
  CONSTRAINT new_lead_outbox_fpver_ck       CHECK (fingerprint_version = 1),
  CONSTRAINT new_lead_outbox_event_type_ck  CHECK (event_type = 'NEW_LEAD'),
  CONSTRAINT new_lead_outbox_route_ck       CHECK (request_route IN ('public','concierge','miniapp')),
  CONSTRAINT new_lead_outbox_lead_id_ck     CHECK (lead_id <> '' AND length(lead_id) <= 64),

  -- ALLOWLIST, enforced in the database as well as in the function. An unknown key fails the
  -- insert rather than being stored and forgotten.
  --
  -- AMENDMENT 2.1-B (real-Postgres proof, §16). The revision-2 form used
  -- `NOT EXISTS (SELECT 1 FROM jsonb_object_keys(...))`. PostgreSQL rejects that outright:
  -- 0A000 "cannot use subquery in check constraint". The table could not be created at all,
  -- so the "enforced twice" claim was unbuilt. `jsonb - text[]` deletes the allowed keys and is
  -- an IMMUTABLE operator with no subquery: if anything is left over, a key was not on the list.
  CONSTRAINT new_lead_outbox_payload_allowlist_ck CHECK (
    jsonb_typeof(payload_json) = 'object'
    AND (payload_json - ARRAY['company','role','objective','situation','priority','zone',
                              'next_action','source','contact_channel','contact_value','lead_id'])
        = '{}'::jsonb
  ),
  CONSTRAINT new_lead_outbox_contact_channel_ck CHECK (
    payload_json->>'contact_channel' IS NULL
    OR payload_json->>'contact_channel' IN ('telegram','phone','email','none')
  ),
  -- A purged row carries NOTHING, not merely "no contact_value". The 30-day window covers the
  -- whole presentation payload, so the post-purge shape is a single, checkable value.
  CONSTRAINT new_lead_outbox_purge_ck CHECK (
    payload_purged_at IS NULL OR payload_json = '{}'::jsonb
  )
);
ALTER TABLE alerts.new_lead_outbox OWNER TO alerts_owner;

COMMENT ON TABLE alerts.new_lead_outbox IS
  'One row per AUTHORITATIVE NEW LEAD, written after Lead Intake''s Save to Pipeline succeeds. '
  'The row is the durable INTENT to notify; it is not a delivery record and never a lead record. '
  'It stores a SHA-256 fingerprint of the canonical request id, never the id itself.';
COMMENT ON COLUMN alerts.new_lead_outbox.request_fingerprint IS
  'sha256(''finmentor:new_lead:v1:'' || canonical_request_id), lower hex. Computed by '
  'alerts.request_fingerprint inside alerts.enqueue_new_lead. NEVER accepted from a caller. '
  'Pseudonymous, NOT anonymous — see docs 2.4.';
COMMENT ON COLUMN alerts.new_lead_outbox.dispatch_key IS
  'NEW_LEAD:<request_fingerprint>. GENERATED ALWAYS, so no writer can choose it.';
COMMENT ON COLUMN alerts.new_lead_outbox.payload_json IS
  'The approved NEW LEAD presentation snapshot, allowlisted by constraint. Contains ONE contact '
  'value, which may itself be a phone number, an email address or a Telegram handle depending on '
  'contact_channel. Purged to ''{}'' at the payload retention horizon. Never a raw webhook body, '
  'raw_json, draft envelope, initData, signature material or execution payload.';
COMMENT ON COLUMN alerts.new_lead_outbox.settled_at IS
  'When Lead Intake settled the lead (Save to Pipeline success), not when this row was written.';

CREATE INDEX IF NOT EXISTS new_lead_outbox_created_idx  ON alerts.new_lead_outbox (created_at DESC);
CREATE INDEX IF NOT EXISTS new_lead_outbox_lead_idx     ON alerts.new_lead_outbox (lead_id);
CREATE INDEX IF NOT EXISTS new_lead_outbox_unpurged_idx ON alerts.new_lead_outbox (settled_at)
  WHERE payload_purged_at IS NULL;

-- ------------------------------------------------------------- the delivery
CREATE TABLE IF NOT EXISTS alerts.new_lead_delivery (
  dispatch_key        text        NOT NULL,
  channel             text        NOT NULL,
  status              text        NOT NULL DEFAULT 'PENDING',
  claim_token         uuid,
  claimed_at          timestamptz,
  attempt_count       integer     NOT NULL DEFAULT 0,
  next_attempt_at     timestamptz NOT NULL DEFAULT now(),
  last_error_code     text,
  provider_message_id text,
  sent_at             timestamptz,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT new_lead_delivery_pk PRIMARY KEY (dispatch_key, channel),
  CONSTRAINT new_lead_delivery_fk FOREIGN KEY (dispatch_key)
    REFERENCES alerts.new_lead_outbox (dispatch_key) ON DELETE RESTRICT,

  CONSTRAINT new_lead_delivery_channel_ck CHECK (channel IN ('telegram','email')),
  CONSTRAINT new_lead_delivery_status_ck  CHECK (status IN
    ('PENDING','CLAIMED','SENT','RETRYABLE_FAILED','DELIVERY_UNKNOWN','PERMANENT_FAILED')),
  CONSTRAINT new_lead_delivery_attempts_ck CHECK (attempt_count >= 0 AND attempt_count <= 1000),
  CONSTRAINT new_lead_delivery_error_ck    CHECK (last_error_code IS NULL
                                                  OR last_error_code ~ '^[A-Z][A-Z0-9_]{2,39}$'),
  CONSTRAINT new_lead_delivery_provider_len_ck CHECK (
    provider_message_id IS NULL OR length(provider_message_id) <= 512),

  -- STATE INVARIANTS, so an impossible row cannot be written by any worker.
  CONSTRAINT new_lead_delivery_sent_ck CHECK (
    status <> 'SENT' OR (sent_at IS NOT NULL AND claim_token IS NULL)),
  CONSTRAINT new_lead_delivery_claim_ck CHECK (
    (status = 'CLAIMED' AND claim_token IS NOT NULL AND claimed_at IS NOT NULL)
    OR (status <> 'CLAIMED' AND claim_token IS NULL)),
  CONSTRAINT new_lead_delivery_unknown_ck CHECK (
    status <> 'DELIVERY_UNKNOWN' OR attempt_count > 0),
  CONSTRAINT new_lead_delivery_provider_ck CHECK (
    provider_message_id IS NULL OR status IN ('SENT','DELIVERY_UNKNOWN'))
);
ALTER TABLE alerts.new_lead_delivery OWNER TO alerts_owner;

COMMENT ON TABLE alerts.new_lead_delivery IS
  'One row per (event, channel). Telegram and Email are SEPARATE ROWS, not columns: "a retry of '
  'Email must never resend Telegram" is then a constraint — the claim WHERE matches one row and '
  'that row is one channel — rather than a convention an UPDATE has to remember.';
COMMENT ON COLUMN alerts.new_lead_delivery.provider_message_id IS
  'PROVIDER-NEUTRAL and OPTIONAL. Recorded only if the provider returns one. Microsoft Graph '
  'sendMail answers 202 Accepted with no body and no id, so it will usually be NULL; no id is '
  'ever invented. Never a credential, never a URL, never a tenant or mailbox identifier.';

CREATE INDEX IF NOT EXISTS new_lead_delivery_claimable_idx
  ON alerts.new_lead_delivery (channel, next_attempt_at)
  WHERE status IN ('PENDING','RETRYABLE_FAILED');
CREATE INDEX IF NOT EXISTS new_lead_delivery_attention_idx
  ON alerts.new_lead_delivery (status, updated_at)
  WHERE status IN ('DELIVERY_UNKNOWN','PERMANENT_FAILED');
CREATE INDEX IF NOT EXISTS new_lead_delivery_claimed_idx
  ON alerts.new_lead_delivery (claimed_at) WHERE status = 'CLAIMED';

CREATE OR REPLACE FUNCTION alerts.touch_updated_at() RETURNS trigger
  LANGUAGE plpgsql SET search_path = pg_catalog AS $fn$
BEGIN NEW.updated_at := now(); RETURN NEW; END;
$fn$;
ALTER FUNCTION alerts.touch_updated_at() OWNER TO alerts_owner;

DROP TRIGGER IF EXISTS new_lead_delivery_touch ON alerts.new_lead_delivery;
CREATE TRIGGER new_lead_delivery_touch BEFORE UPDATE ON alerts.new_lead_delivery
  FOR EACH ROW EXECUTE FUNCTION alerts.touch_updated_at();

-- --------------------------------------------- the retention AND repair policy
-- One row. It exists so that every operational horizon in this schema is DATA the code reads,
-- not a constant compiled into it. Two of them are OWNER-APPROVED (payload 30 d, delivery
-- 180 d), one is an OWNER-APPROVED BUSINESS RULE (automatic repair 7 d), and two are
-- deliberately UNDECIDED (the key horizon, the DELIVERY_UNKNOWN horizon) — held as NULL with an
-- explicit status, so neither can quietly become "forever" and neither can quietly start
-- deleting.
--
-- AMENDMENT 2.2-B (owner decision). automatic_repair_days was `interval '7 days'` written into
-- the body of alerts.enqueue_new_lead. 7 days is approved, but a business policy inside a
-- CREATE FUNCTION body can only be changed by a migration -- so it moved here.
-- AMENDMENT 2.2-C (owner decision). The DELIVERY_UNKNOWN horizon is now recorded as pending
-- rather than merely absent from a WHERE clause.
CREATE TABLE IF NOT EXISTS alerts.retention_policy (
  singleton               boolean PRIMARY KEY DEFAULT true CHECK (singleton),
  payload_retention_days  integer NOT NULL DEFAULT 30
                            CHECK (payload_retention_days BETWEEN 1 AND 3650),
  delivery_retention_days integer NOT NULL DEFAULT 180
                            CHECK (delivery_retention_days BETWEEN 1 AND 3650),
  -- OWNER-APPROVED BUSINESS RULE, 2026-09-01. Beyond this age an ordinary enqueue will NOT
  -- restore a missing delivery row: a NEW LEAD alert older than the window must not be
  -- resurrected and sent as if it were fresh. Only alerts.repair_new_lead_deliveries() -- the
  -- explicit reconciler authority -- may do so afterwards.
  automatic_repair_days   integer NOT NULL DEFAULT 7
                            CHECK (automatic_repair_days BETWEEN 1 AND 365),
  key_retention_days      integer CHECK (key_retention_days IS NULL OR key_retention_days >= 30),
  key_retention_status    text NOT NULL DEFAULT 'PENDING_LEGAL_PRIVACY_FINALISATION'
                            CHECK (key_retention_status IN ('PENDING_LEGAL_PRIVACY_FINALISATION',
                                                            'DECIDED_BOUNDED','DECIDED_INDEFINITE')),
  -- UNDECIDED, and deliberately so. A DELIVERY_UNKNOWN row is an unresolved question about
  -- whether the owner was notified; deleting it destroys the question rather than answering it.
  delivery_unknown_retention_days   integer
                            CHECK (delivery_unknown_retention_days IS NULL
                                   OR delivery_unknown_retention_days BETWEEN 1 AND 3650),
  delivery_unknown_retention_status text NOT NULL DEFAULT 'PENDING_OWNER'
                            CHECK (delivery_unknown_retention_status IN
                                   ('PENDING_OWNER','DECIDED_BOUNDED')),
  decided_at              timestamptz,
  updated_at              timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT retention_key_decision_ck CHECK (
       (key_retention_status = 'DECIDED_BOUNDED'    AND key_retention_days IS NOT NULL)
    OR (key_retention_status <> 'DECIDED_BOUNDED'   AND key_retention_days IS NULL)),
  CONSTRAINT retention_delivery_unknown_decision_ck CHECK (
       (delivery_unknown_retention_status = 'DECIDED_BOUNDED'
          AND delivery_unknown_retention_days IS NOT NULL)
    OR (delivery_unknown_retention_status = 'PENDING_OWNER'
          AND delivery_unknown_retention_days IS NULL))
);
ALTER TABLE alerts.retention_policy OWNER TO alerts_owner;
INSERT INTO alerts.retention_policy (singleton) VALUES (true) ON CONFLICT DO NOTHING;

COMMENT ON TABLE alerts.retention_policy IS
  'Single-row retention AND repair configuration. payload 30 d, delivery 180 d and automatic '
  'repair 7 d are OWNER-APPROVED and are DATA: changing any of them is an UPDATE, never a '
  'migration. key_retention_status starts at PENDING_LEGAL_PRIVACY_FINALISATION and '
  'key_retention_days is NULL: alerts.purge_new_lead_keys() refuses to run in that state. '
  'delivery_unknown_retention_status starts at PENDING_OWNER and '
  'alerts.purge_new_lead_deliveries() refuses to run if it ever changes without the deletion '
  'code being written. Nothing in this schema assumes "retain forever" — the two open horizons '
  'are undecided, and the code says so in both directions.';
COMMENT ON COLUMN alerts.retention_policy.automatic_repair_days IS
  'OWNER-APPROVED BUSINESS RULE (7). The age beyond which alerts.enqueue_new_lead will not '
  'recreate a missing delivery row. Read on every call; changing it changes behaviour with no '
  'schema or function migration. Beyond it, repair is alerts.repair_new_lead_deliveries() only.';

CREATE OR REPLACE FUNCTION alerts.enqueue_new_lead(
  p_request_route text,
  p_request_id    text,          -- RAW canonical identity. TRANSIENT. Never stored.
  p_lead_id       text,
  p_settled_at    timestamptz,
  p_payload       jsonb
) RETURNS TABLE (
  out_dispatch_key        text,
  out_request_fingerprint text,
  out_outcome             text,
  out_telegram_created    boolean,
  out_email_created       boolean
)
LANGUAGE plpgsql VOLATILE SECURITY DEFINER
SET search_path = pg_catalog
AS $fn$
DECLARE
  v_fp text; v_key text; v_n integer;
  v_created boolean := false; v_tg boolean := false; v_mail boolean := false;
  v_settled timestamptz; v_nbad integer; v_outcome text;
  v_ev integer; v_tgn integer; v_mailn integer;
  -- Repair horizon. Beyond this a MISSING delivery row is not recreated automatically: a NEW
  -- LEAD alert older than the window must not be resurrected and sent as if it were fresh, and
  -- delivery rows are purged at 180 days (§12), so a blind repair would resend a year-old alert.
  -- Beyond-horizon repair is the reconciler's explicit function, not a side effect of enqueue.
  --
  -- AMENDMENT 2.2-B (owner decision). This was a CONSTANT interval of seven days, written into
  -- the function body. The WINDOW IS APPROVED; compiling it in was not. It is now read from
  -- alerts.retention_policy on every call, so changing an approved business policy is an UPDATE
  -- of one integer, not a function migration. The read is inside the same transaction as the
  -- write it governs, so a concurrent policy change cannot half-apply.
  v_repair_days integer;
BEGIN
  ---------------------------------------------------------------- 1. route
  IF p_request_route IS NULL OR p_request_route NOT IN ('public','concierge','miniapp') THEN
    RAISE EXCEPTION 'ALERTS_ROUTE_INVALID' USING ERRCODE = '22023';
  END IF;

  ------------------------------------------------- 2. canonical identity shape
  -- Validated HERE because the raw value is never stored and can therefore never be checked
  -- by a table constraint afterwards. The message NEVER echoes p_request_id: it is the very
  -- identifier this design exists to keep out of durable stores, and Postgres logs are durable.
  IF p_request_id IS NULL
     OR NOT (
          (p_request_route = 'public'    AND p_request_id ~ '^fmr_[0-9a-f]{32}$')
       OR (p_request_route = 'miniapp'   AND p_request_id ~ '^sub_[0-9a-f]{32}$')
       OR (p_request_route = 'concierge' AND p_request_id ~ '^C--?[0-9]{1,20}-[0-9]{10,16}$')
     ) THEN
    RAISE EXCEPTION 'ALERTS_REQUEST_ID_SHAPE_INVALID (route=%)', p_request_route
      USING ERRCODE = '22023';
  END IF;

  ------------------------------------------------------------- 3. lead + time
  IF p_lead_id IS NULL OR p_lead_id = '' OR length(p_lead_id) > 64 THEN
    RAISE EXCEPTION 'ALERTS_LEAD_ID_INVALID' USING ERRCODE = '22023';
  END IF;
  IF p_settled_at IS NULL
     OR p_settled_at > now() + interval '5 minutes'
     OR p_settled_at < timestamptz '2025-01-01' THEN
    RAISE EXCEPTION 'ALERTS_SETTLED_AT_INVALID' USING ERRCODE = '22023';
  END IF;

  --------------------------------------------------- 4. allowlisted payload
  IF p_payload IS NULL OR jsonb_typeof(p_payload) <> 'object' THEN
    RAISE EXCEPTION 'ALERTS_PAYLOAD_NOT_OBJECT' USING ERRCODE = '22023';
  END IF;
  SELECT count(*) INTO v_nbad
    FROM jsonb_object_keys(p_payload) AS t(k)
   WHERE k NOT IN ('company','role','objective','situation','priority','zone',
                   'next_action','source','contact_channel','contact_value','lead_id');
  IF v_nbad > 0 THEN
    -- AMENDMENT 2.2-D (defect found in the revision-2.2 pass). Revision 2.1 echoed the offending
    -- KEY NAMES here, on the reasoning that "key names are safe to echo; values are not".
    -- They are not safe: a JSON key is a caller-controlled string, so {"C-123456789-1788000000000": 1}
    -- put a raw Concierge identity — the exact value this whole design exists to keep out of
    -- durable stores — into an error message. finmentor-prod runs log_min_error_statement = error,
    -- so that message and its statement reach a durable server log. Only the COUNT is reported
    -- now. The caller knows what it sent; the log does not need to.
    RAISE EXCEPTION 'ALERTS_PAYLOAD_KEY_FORBIDDEN (n=%)', v_nbad USING ERRCODE = '22023';
  END IF;
  IF p_payload ? 'contact_channel'
     AND p_payload->>'contact_channel' NOT IN ('telegram','phone','email','none') THEN
    RAISE EXCEPTION 'ALERTS_CONTACT_CHANNEL_INVALID' USING ERRCODE = '22023';
  END IF;

  ------------------------------------------------- 5. fingerprint and the key
  v_fp  := alerts.request_fingerprint(p_request_id);
  v_key := 'NEW_LEAD:' || v_fp;

  ------------------------------------------------ 5b. the repair policy, as data
  -- AMENDMENT 2.2-B. Read, never compiled in. If the policy row is missing the function REFUSES
  -- rather than falling back to a hard-coded default: a silent default is exactly how a business
  -- rule gets buried in SQL again.
  SELECT automatic_repair_days INTO v_repair_days
    FROM alerts.retention_policy WHERE singleton;
  IF v_repair_days IS NULL THEN
    RAISE EXCEPTION 'ALERTS_REPAIR_POLICY_MISSING' USING ERRCODE = 'P0002';
  END IF;

  ------------------------------------------------------- 6. the event, safely
  INSERT INTO alerts.new_lead_outbox
    (request_fingerprint, fingerprint_version, event_type, request_route,
     lead_id, schema_version, settled_at, payload_json)
  VALUES (v_fp, 1, 'NEW_LEAD', p_request_route,
          p_lead_id, 1, p_settled_at, p_payload)
  -- AMENDMENT 2.1-C (real-Postgres proof, §16). NO arbiter index is named. dispatch_key carries
  -- its own unique index — the PRIMARY KEY — perfectly correlated with request_fingerprint.
  -- Naming only the fingerprint made the speculative insert arbitrate on one index while the
  -- other still raised: a 6-way concurrent burst on one identity produced three bare
  -- 23505 "duplicate key value violates unique constraint new_lead_outbox_pk" errors instead of
  -- ALREADY_PRESENT. The final state was still 1 + 1 + 1, but the caller received an
  -- unclassified error — and §8 says the dispatcher can only classify on ALERTS_* prefixes,
  -- because the n8n Postgres node hides SQLSTATE. Unqualified ON CONFLICT DO NOTHING arbitrates
  -- on EVERY unique index. Never DO UPDATE: an event is not editable.
  ON CONFLICT DO NOTHING;
  GET DIAGNOSTICS v_n = ROW_COUNT;
  v_created := (v_n = 1);

  SELECT o.settled_at INTO v_settled
    FROM alerts.new_lead_outbox o WHERE o.request_fingerprint = v_fp;
  IF v_settled IS NULL THEN
    -- ON CONFLICT DO NOTHING lost a race with a transaction that then aborted. Ask the caller
    -- to retry rather than silently return "already present" for a row that does not exist.
    RAISE EXCEPTION 'ALERTS_ENQUEUE_RACE_RETRY' USING ERRCODE = '40001';
  END IF;

  --------------------------------------- 7 + 8. both delivery rows, same tx
  IF v_created OR v_settled >= now() - make_interval(days => v_repair_days) THEN
    INSERT INTO alerts.new_lead_delivery (dispatch_key, channel) VALUES (v_key, 'telegram')
      ON CONFLICT (dispatch_key, channel) DO NOTHING;
    GET DIAGNOSTICS v_n = ROW_COUNT; v_tg := (v_n = 1);

    INSERT INTO alerts.new_lead_delivery (dispatch_key, channel) VALUES (v_key, 'email')
      ON CONFLICT (dispatch_key, channel) DO NOTHING;
    GET DIAGNOSTICS v_n = ROW_COUNT; v_mail := (v_n = 1);

    -- CONVERGENCE, ASSERTED. If this transaction would commit anything other than exactly
    -- 1 event + 1 telegram + 1 email, it commits NOTHING. The crash window the owner named
    -- cannot exist as a committed state.
    SELECT count(*) INTO v_ev
      FROM alerts.new_lead_outbox WHERE request_fingerprint = v_fp;
    SELECT count(*) FILTER (WHERE channel = 'telegram'),
           count(*) FILTER (WHERE channel = 'email')
      INTO v_tgn, v_mailn
      FROM alerts.new_lead_delivery WHERE dispatch_key = v_key;
    IF v_ev <> 1 OR v_tgn <> 1 OR v_mailn <> 1 THEN
      RAISE EXCEPTION 'ALERTS_ENQUEUE_NOT_CONVERGENT (event=% telegram=% email=%)',
        v_ev, v_tgn, v_mailn USING ERRCODE = '25000';
    END IF;

    v_outcome := CASE WHEN v_created        THEN 'CREATED'
                      WHEN v_tg OR v_mail   THEN 'REPAIRED'
                      ELSE                       'ALREADY_PRESENT' END;
  ELSE
    v_outcome := 'EVENT_EXISTS_OUTSIDE_REPAIR_WINDOW';
  END IF;

  RETURN QUERY SELECT v_key, v_fp, v_outcome, v_tg, v_mail;
END;
$fn$;
ALTER FUNCTION alerts.enqueue_new_lead(text,text,text,timestamptz,jsonb) OWNER TO alerts_owner;

COMMENT ON FUNCTION alerts.enqueue_new_lead(text,text,text,timestamptz,jsonb) IS
  'THE ENQUEUE TRANSACTION BOUNDARY. Validates the route identity, computes the fingerprint, '
  'derives the key, validates the allowlisted payload, and creates the event plus BOTH channel '
  'rows in ONE transaction. Convergent: calling it again for the same canonical request leaves '
  'exactly 1 event + 1 telegram + 1 email, and restores a missing delivery row without '
  'duplicating anything, within alerts.retention_policy.automatic_repair_days. Never updates an '
  'existing event. p_request_id is TRANSIENT: RAW REQUEST_ID PERSISTED IN ALERTS = NO — no '
  'column holds it and no error message echoes it. It DOES reach the server as a function '
  'argument, so it is subject to whatever the cluster''s statement and parameter logging is set '
  'to; see docs 2.6. This function cannot and does not claim otherwise.';

-- Comma-safe wrapper. The deployed n8n Postgres node splits queryReplacement on COMMAS BEFORE
-- resolving expressions, so a JSON payload — which is nothing but commas — cannot be passed as
-- a bound parameter. Base64 has no commas. This is the call the runtime uses.
CREATE OR REPLACE FUNCTION alerts.enqueue_new_lead_b64(
  p_request_route text, p_request_id text, p_lead_id text,
  p_settled_at timestamptz, p_payload_b64 text
) RETURNS TABLE (
  out_dispatch_key text, out_request_fingerprint text, out_outcome text,
  out_telegram_created boolean, out_email_created boolean
)
LANGUAGE sql VOLATILE
SET search_path = pg_catalog
AS $fn$
  SELECT * FROM alerts.enqueue_new_lead(
    p_request_route, p_request_id, p_lead_id, p_settled_at,
    convert_from(decode(p_payload_b64, 'base64'), 'UTF8')::jsonb);
$fn$;
ALTER FUNCTION alerts.enqueue_new_lead_b64(text,text,text,timestamptz,text) OWNER TO alerts_owner;

-- ---------------------------------------------------------- claim (dispatcher)
CREATE OR REPLACE FUNCTION alerts.claim_new_lead_delivery(
  p_channel text, p_max_attempts integer DEFAULT 8
) RETURNS TABLE (
  out_dispatch_key text, out_channel text, out_claim_token uuid, out_attempt_count integer,
  out_lead_id text, out_request_route text, out_settled_at timestamptz, out_payload_json jsonb
)
LANGUAGE plpgsql VOLATILE SECURITY DEFINER
SET search_path = pg_catalog
AS $fn$
BEGIN
  IF p_channel IS NULL OR p_channel NOT IN ('telegram','email') THEN
    RAISE EXCEPTION 'ALERTS_CHANNEL_INVALID' USING ERRCODE = '22023';
  END IF;
  RETURN QUERY
  WITH candidate AS (
    SELECT d.dispatch_key, d.channel
      FROM alerts.new_lead_delivery d
      JOIN alerts.new_lead_outbox   o ON o.dispatch_key = d.dispatch_key
     WHERE d.channel = p_channel
       AND d.status IN ('PENDING','RETRYABLE_FAILED')
       AND d.next_attempt_at <= now()
       AND d.attempt_count < p_max_attempts
       AND o.payload_purged_at IS NULL        -- a purged event cannot be rendered; §12, gate 31
     ORDER BY d.next_attempt_at
     FOR UPDATE OF d SKIP LOCKED
     LIMIT 1
  ), claimed AS (
    UPDATE alerts.new_lead_delivery d
       SET status = 'CLAIMED', claim_token = gen_random_uuid(), claimed_at = now(),
           attempt_count = d.attempt_count + 1
      FROM candidate c
     WHERE d.dispatch_key = c.dispatch_key AND d.channel = c.channel
       AND d.status IN ('PENDING','RETRYABLE_FAILED')
    RETURNING d.dispatch_key, d.channel, d.claim_token, d.attempt_count
  )
  SELECT c.dispatch_key, c.channel, c.claim_token, c.attempt_count,
         o.lead_id, o.request_route, o.settled_at, o.payload_json
    FROM claimed c JOIN alerts.new_lead_outbox o ON o.dispatch_key = c.dispatch_key;
END;
$fn$;
ALTER FUNCTION alerts.claim_new_lead_delivery(text,integer) OWNER TO alerts_owner;

-- ------------------------------------------------------- finalise (dispatcher)
CREATE OR REPLACE FUNCTION alerts.finalise_new_lead_delivery(
  p_dispatch_key text, p_channel text, p_claim_token uuid, p_outcome text,
  p_error_code text DEFAULT NULL, p_provider_message_id text DEFAULT NULL,
  p_retry_after interval DEFAULT NULL
) RETURNS text
LANGUAGE plpgsql VOLATILE SECURITY DEFINER
SET search_path = pg_catalog
AS $fn$
DECLARE v_att integer; v_next timestamptz; v_n integer;
BEGIN
  IF p_outcome NOT IN ('SENT','RETRYABLE_FAILED','DELIVERY_UNKNOWN','PERMANENT_FAILED') THEN
    RAISE EXCEPTION 'ALERTS_OUTCOME_INVALID' USING ERRCODE = '22023';
  END IF;
  IF p_error_code IS NOT NULL AND p_error_code !~ '^[A-Z][A-Z0-9_]{2,39}$' THEN
    RAISE EXCEPTION 'ALERTS_ERROR_CODE_INVALID' USING ERRCODE = '22023';
  END IF;
  IF p_provider_message_id IS NOT NULL
     AND (length(p_provider_message_id) > 512 OR p_outcome NOT IN ('SENT','DELIVERY_UNKNOWN')) THEN
    RAISE EXCEPTION 'ALERTS_PROVIDER_ID_INVALID' USING ERRCODE = '22023';
  END IF;

  SELECT d.attempt_count INTO v_att FROM alerts.new_lead_delivery d
   WHERE d.dispatch_key = p_dispatch_key AND d.channel = p_channel
     AND d.claim_token = p_claim_token AND d.status = 'CLAIMED';
  IF v_att IS NULL THEN RETURN 'NOT_OWNED'; END IF;   -- no token, no write. Never "assume ours".

  v_next := now() + LEAST(
              GREATEST(COALESCE(p_retry_after,
                                make_interval(mins => (2 ^ LEAST(v_att, 6))::integer)),
                       interval '30 seconds'),
              interval '6 hours');

  UPDATE alerts.new_lead_delivery d
     SET status              = p_outcome,
         claim_token         = NULL,
         sent_at             = CASE WHEN p_outcome = 'SENT' THEN now() ELSE d.sent_at END,
         next_attempt_at     = CASE WHEN p_outcome = 'RETRYABLE_FAILED'
                                    THEN v_next ELSE d.next_attempt_at END,
         last_error_code     = CASE WHEN p_outcome = 'SENT' THEN NULL ELSE p_error_code END,
         provider_message_id = COALESCE(p_provider_message_id, d.provider_message_id)
   WHERE d.dispatch_key = p_dispatch_key AND d.channel = p_channel
     AND d.claim_token = p_claim_token AND d.status = 'CLAIMED';
  GET DIAGNOSTICS v_n = ROW_COUNT;
  RETURN CASE WHEN v_n = 1 THEN 'OK' ELSE 'NOT_OWNED' END;
END;
$fn$;
ALTER FUNCTION alerts.finalise_new_lead_delivery(text,text,uuid,text,text,text,interval)
  OWNER TO alerts_owner;

-- A worker that died holding a claim may already have sent. The row therefore becomes
-- DELIVERY_UNKNOWN — NOT RETRYABLE_FAILED — and is never reclaimed automatically.
CREATE OR REPLACE FUNCTION alerts.expire_stale_claims(p_older_than interval DEFAULT interval '15 minutes')
RETURNS integer
LANGUAGE plpgsql VOLATILE SECURITY DEFINER
SET search_path = pg_catalog
AS $fn$
DECLARE v_n integer;
BEGIN
  IF p_older_than < interval '1 minute' THEN
    RAISE EXCEPTION 'ALERTS_EXPIRY_TOO_SHORT' USING ERRCODE = '22023';
  END IF;
  UPDATE alerts.new_lead_delivery
     SET status = 'DELIVERY_UNKNOWN', claim_token = NULL, last_error_code = 'CLAIM_EXPIRED'
   WHERE status = 'CLAIMED' AND claimed_at < now() - p_older_than;
  GET DIAGNOSTICS v_n = ROW_COUNT;
  RETURN v_n;
END;
$fn$;
ALTER FUNCTION alerts.expire_stale_claims(interval) OWNER TO alerts_owner;

-- ---------------------------------------------------- attention (dispatcher/audit)
-- No payload. This is the SYSTEM ALERT feed, and it carries no PII.
CREATE OR REPLACE FUNCTION alerts.new_lead_attention()
RETURNS TABLE (out_dispatch_key text, out_channel text, out_status text, out_reason text,
               out_attempt_count integer, out_last_error_code text,
               out_request_route text, out_settled_at timestamptz, out_updated_at timestamptz)
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = pg_catalog
AS $fn$
  SELECT d.dispatch_key, d.channel, d.status,
         CASE WHEN d.status = 'DELIVERY_UNKNOWN'                      THEN 'DELIVERY_UNKNOWN'
              WHEN d.status = 'PERMANENT_FAILED'                      THEN 'PERMANENT_FAILED'
              WHEN d.status = 'CLAIMED'                               THEN 'CLAIM_STUCK'
              ELSE 'UNDELIVERED_PAYLOAD_PURGED' END,
         d.attempt_count, d.last_error_code, o.request_route, o.settled_at, d.updated_at
    FROM alerts.new_lead_delivery d
    JOIN alerts.new_lead_outbox   o ON o.dispatch_key = d.dispatch_key
   WHERE d.status IN ('DELIVERY_UNKNOWN','PERMANENT_FAILED')
      OR (d.status = 'CLAIMED' AND d.claimed_at < now() - interval '15 minutes')
      OR (d.status IN ('PENDING','RETRYABLE_FAILED') AND o.payload_purged_at IS NOT NULL)
   ORDER BY d.updated_at;
$fn$;
ALTER FUNCTION alerts.new_lead_attention() OWNER TO alerts_owner;

-- ------------------------------------------------------------- reconciler
-- Deterministic presence check. Takes RAW Pipeline request ids transiently, hashes them by the
-- same contract, returns which are missing. Stores nothing. NO FUZZY MATCHING anywhere.
CREATE OR REPLACE FUNCTION alerts.new_lead_events_present(p_request_ids text[])
RETURNS TABLE (out_request_id text, out_request_fingerprint text, out_present boolean)
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = pg_catalog
AS $fn$
  SELECT r.rid,
         alerts.request_fingerprint(r.rid),
         EXISTS (SELECT 1 FROM alerts.new_lead_outbox o
                  WHERE o.request_fingerprint = alerts.request_fingerprint(r.rid))
    FROM unnest(p_request_ids) AS r(rid)
   WHERE r.rid IS NOT NULL AND r.rid <> '';
$fn$;
ALTER FUNCTION alerts.new_lead_events_present(text[]) OWNER TO alerts_owner;

-- Beyond-horizon delivery repair. EXPLICIT, reconciler only — enqueue deliberately will not do
-- this by itself, because a delivery row missing because it was PURGED at 180 days must not be
-- silently recreated and resent.
CREATE OR REPLACE FUNCTION alerts.repair_new_lead_deliveries(p_dispatch_key text)
RETURNS TABLE (out_telegram_created boolean, out_email_created boolean)
LANGUAGE plpgsql VOLATILE SECURITY DEFINER
SET search_path = pg_catalog
AS $fn$
DECLARE v_n integer; v_tg boolean := false; v_mail boolean := false;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM alerts.new_lead_outbox WHERE dispatch_key = p_dispatch_key) THEN
    RAISE EXCEPTION 'ALERTS_EVENT_NOT_FOUND' USING ERRCODE = '23503';
  END IF;
  INSERT INTO alerts.new_lead_delivery (dispatch_key, channel) VALUES (p_dispatch_key, 'telegram')
    ON CONFLICT (dispatch_key, channel) DO NOTHING;
  GET DIAGNOSTICS v_n = ROW_COUNT; v_tg := (v_n = 1);
  INSERT INTO alerts.new_lead_delivery (dispatch_key, channel) VALUES (p_dispatch_key, 'email')
    ON CONFLICT (dispatch_key, channel) DO NOTHING;
  GET DIAGNOSTICS v_n = ROW_COUNT; v_mail := (v_n = 1);
  RETURN QUERY SELECT v_tg, v_mail;
END;
$fn$;
ALTER FUNCTION alerts.repair_new_lead_deliveries(text) OWNER TO alerts_owner;

-- ------------------------------------------------------------- retention
CREATE OR REPLACE FUNCTION alerts.purge_new_lead_payloads()
RETURNS integer
LANGUAGE plpgsql VOLATILE SECURITY DEFINER
SET search_path = pg_catalog
AS $fn$
DECLARE v_days integer; v_n integer;
BEGIN
  SELECT payload_retention_days INTO v_days FROM alerts.retention_policy WHERE singleton;
  UPDATE alerts.new_lead_outbox
     SET payload_json = '{}'::jsonb, payload_purged_at = now()
   WHERE payload_purged_at IS NULL
     AND settled_at < now() - make_interval(days => v_days);
  GET DIAGNOSTICS v_n = ROW_COUNT;
  RETURN v_n;
END;
$fn$;
ALTER FUNCTION alerts.purge_new_lead_payloads() OWNER TO alerts_owner;

CREATE OR REPLACE FUNCTION alerts.purge_new_lead_deliveries()
RETURNS integer
LANGUAGE plpgsql VOLATILE SECURITY DEFINER
SET search_path = pg_catalog
AS $fn$
DECLARE v_days integer; v_n integer; v_du_status text;
BEGIN
  SELECT delivery_retention_days, delivery_unknown_retention_status
    INTO v_days, v_du_status
    FROM alerts.retention_policy WHERE singleton;
  -- AMENDMENT 2.2-C (owner decision). The DELIVERY_UNKNOWN horizon is UNDECIDED, and this
  -- function refuses to run if that ever stops being true, because the deletion code for it does
  -- NOT exist. Without this, recording a decision would silently do nothing -- the pending
  -- horizon would become unbounded by implementation accident, which is exactly what the owner
  -- ruled out. The guard fails loudly instead, and whoever records the decision is told the
  -- sweep has not been written yet.
  IF v_du_status <> 'PENDING_OWNER' THEN
    RAISE EXCEPTION 'ALERTS_DELIVERY_UNKNOWN_HORIZON_NOT_IMPLEMENTED (status=%)', v_du_status
      USING ERRCODE = '0A000';
  END IF;
  -- TERMINAL rows only. A DELIVERY_UNKNOWN still awaiting an owner decision is never swept, and
  -- neither is a CLAIMED, PENDING or RETRYABLE_FAILED row: this deletes settled history, not
  -- outstanding work. The payload behind an unresolved DELIVERY_UNKNOWN is still purged at 30
  -- days by alerts.purge_new_lead_payloads(), so an unresolved delivery does NOT keep
  -- contact_value alive indefinitely (gate 58).
  DELETE FROM alerts.new_lead_delivery
   WHERE status IN ('SENT','PERMANENT_FAILED')
     AND updated_at < now() - make_interval(days => v_days);
  GET DIAGNOSTICS v_n = ROW_COUNT;
  RETURN v_n;
END;
$fn$;
ALTER FUNCTION alerts.purge_new_lead_deliveries() OWNER TO alerts_owner;
COMMENT ON FUNCTION alerts.purge_new_lead_deliveries() IS
  'Deletes TERMINAL delivery rows (SENT, PERMANENT_FAILED) older than '
  'alerts.retention_policy.delivery_retention_days. DELIVERY_UNKNOWN RETENTION = PENDING OWNER: '
  'those rows are never automatically reclaimed, never automatically resent and never silently '
  'deleted while unresolved. If delivery_unknown_retention_status ever leaves PENDING_OWNER this '
  'function RAISES, because the sweep it would imply has not been written.';

-- The key horizon is a LEGAL/PRIVACY decision that has not been taken. This function exists so
-- the code path is designed and reviewable, and it REFUSES to run until the decision is recorded.
CREATE OR REPLACE FUNCTION alerts.purge_new_lead_keys()
RETURNS integer
LANGUAGE plpgsql VOLATILE SECURITY DEFINER
SET search_path = pg_catalog
AS $fn$
DECLARE v_status text; v_days integer; v_n integer;
BEGIN
  SELECT key_retention_status, key_retention_days INTO v_status, v_days
    FROM alerts.retention_policy WHERE singleton;
  IF v_status <> 'DECIDED_BOUNDED' OR v_days IS NULL THEN
    RAISE EXCEPTION 'ALERTS_KEY_RETENTION_PENDING_LEGAL_PRIVACY_FINALISATION (status=%)', v_status
      USING ERRCODE = '0A000';
  END IF;
  DELETE FROM alerts.new_lead_outbox o
   WHERE o.settled_at < now() - make_interval(days => v_days)
     AND NOT EXISTS (SELECT 1 FROM alerts.new_lead_delivery d
                      WHERE d.dispatch_key = o.dispatch_key);
  GET DIAGNOSTICS v_n = ROW_COUNT;
  RETURN v_n;
END;
$fn$;
ALTER FUNCTION alerts.purge_new_lead_keys() OWNER TO alerts_owner;
COMMENT ON FUNCTION alerts.purge_new_lead_keys() IS
  'KEY RETENTION = PENDING LEGAL / PRIVACY FINALISATION. Refuses to delete anything until '
  'alerts.retention_policy records DECIDED_BOUNDED with an explicit horizon. Deleting a key '
  'lets a replayed request mint a second business event — that is the trade-off the decision '
  'has to weigh, and this schema does not pre-empt it in either direction.';

-- Audit reads through owner-owned views, so it needs no table privilege and no RLS policy,
-- and the outbox view does not expose the payload at all.
CREATE OR REPLACE VIEW alerts.new_lead_outbox_audit
  WITH (security_invoker = false) AS
  SELECT dispatch_key, request_fingerprint, fingerprint_version, event_type, request_route,
         lead_id, schema_version, settled_at, created_at, payload_purged_at,
         (payload_json ? 'contact_value')   AS has_contact_value,
         (payload_json <> '{}'::jsonb)      AS payload_present
    FROM alerts.new_lead_outbox;

CREATE OR REPLACE VIEW alerts.new_lead_delivery_audit
  WITH (security_invoker = false) AS
  SELECT * FROM alerts.new_lead_delivery;    -- carries no PII by construction

ALTER VIEW alerts.new_lead_outbox_audit   OWNER TO alerts_owner;
ALTER VIEW alerts.new_lead_delivery_audit OWNER TO alerts_owner;

-- ------------------------------------------------------------------ grants
REVOKE ALL ON SCHEMA alerts FROM PUBLIC;
REVOKE ALL ON ALL TABLES    IN SCHEMA alerts FROM PUBLIC;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA alerts FROM PUBLIC;   -- functions grant EXECUTE to
                                                            -- PUBLIC at creation. This is the
                                                            -- statement that takes it back.
ALTER DEFAULT PRIVILEGES FOR ROLE alerts_owner IN SCHEMA alerts
  REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;

-- Supabase's built-in client roles, explicitly, if present. They are granted nothing.
DO $$
DECLARE r text;
BEGIN
  FOREACH r IN ARRAY ARRAY['anon','authenticated','service_role'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
      EXECUTE format('REVOKE ALL ON SCHEMA alerts FROM %I', r);
      EXECUTE format('REVOKE ALL ON ALL TABLES IN SCHEMA alerts FROM %I', r);
      EXECUTE format('REVOKE ALL ON ALL FUNCTIONS IN SCHEMA alerts FROM %I', r);
    END IF;
  END LOOP;
END $$;

GRANT USAGE ON SCHEMA alerts
  TO alerts_writer, alerts_dispatcher, alerts_reconciler, alerts_retention, alerts_audit;

-- NO runtime role receives INSERT, UPDATE, DELETE or SELECT on any table. Not one.
GRANT EXECUTE ON FUNCTION alerts.enqueue_new_lead(text,text,text,timestamptz,jsonb)
  TO alerts_writer, alerts_reconciler;
GRANT EXECUTE ON FUNCTION alerts.enqueue_new_lead_b64(text,text,text,timestamptz,text)
  TO alerts_writer, alerts_reconciler;

GRANT EXECUTE ON FUNCTION alerts.claim_new_lead_delivery(text,integer)      TO alerts_dispatcher;
GRANT EXECUTE ON FUNCTION alerts.finalise_new_lead_delivery(text,text,uuid,text,text,text,interval)
                                                                            TO alerts_dispatcher;
GRANT EXECUTE ON FUNCTION alerts.expire_stale_claims(interval)              TO alerts_dispatcher;
GRANT EXECUTE ON FUNCTION alerts.new_lead_attention()  TO alerts_dispatcher, alerts_audit;

GRANT EXECUTE ON FUNCTION alerts.new_lead_events_present(text[])      TO alerts_reconciler;
GRANT EXECUTE ON FUNCTION alerts.repair_new_lead_deliveries(text)     TO alerts_reconciler;

GRANT EXECUTE ON FUNCTION alerts.purge_new_lead_payloads()   TO alerts_retention;
GRANT EXECUTE ON FUNCTION alerts.purge_new_lead_deliveries() TO alerts_retention;
GRANT EXECUTE ON FUNCTION alerts.purge_new_lead_keys()       TO alerts_retention;

GRANT SELECT ON alerts.new_lead_outbox_audit, alerts.new_lead_delivery_audit TO alerts_audit;

-- alerts.request_fingerprint is granted to NOBODY. The SECURITY DEFINER functions that need it
-- run as its owner. A runtime EXECUTE would only create a hashing oracle.

ALTER TABLE alerts.new_lead_outbox   ENABLE ROW LEVEL SECURITY;
ALTER TABLE alerts.new_lead_delivery ENABLE ROW LEVEL SECURITY;
ALTER TABLE alerts.retention_policy  ENABLE ROW LEVEL SECURITY;
-- ZERO policies, deliberately. And FORCE ROW LEVEL SECURITY is deliberately NOT set:
-- see the proof below. If anyone ever sets it, they must add policies in the same migration
-- or every function in this schema stops returning rows.

-- ------------------------------------ hand the migrator's working membership back
-- AMENDMENT 2.2-A (owner decision). Everything above needed the migrator to be able to SET ROLE
-- alerts_owner: CREATE SCHEMA ... AUTHORIZATION, every ALTER ... OWNER TO, and ALTER DEFAULT
-- PRIVILEGES FOR ROLE. Nothing below does. The membership existed for the migration interval and
-- ends with it, here, before COMMIT -- so a successful migration leaves NO standing ability to
-- act as the owner of this schema.
--
-- WHAT IS DELIBERATELY KEPT, AND WHY: the ADMIN OPTION only. On PostgreSQL 16+ a NOSUPERUSER
-- CREATEROLE migrator -- the finmentor-prod `postgres` shape, confirmed by read-only preflight --
-- can administer a role ONLY through a membership carrying admin_option. Revoking that too would
-- make this migration impossible to re-run and impossible to ROLL BACK without a superuser, and
-- finmentor-prod has no superuser available to us. ADMIN OPTION alone confers neither SET ROLE
-- nor inherited privileges: after this block the migrator CANNOT act as alerts_owner (gate 49).
-- It can grant itself the membership again -- but so can any CREATEROLE role, for any
-- non-superuser role, at any time. That is a property of CREATEROLE, not a hole in this schema,
-- and pretending otherwise would be the kind of claim this document exists to avoid.
DO $$
DECLARE v_me text := current_user;
BEGIN
  EXECUTE format('REVOKE SET OPTION FOR alerts_owner FROM %I', v_me);
  EXECUTE format('REVOKE INHERIT OPTION FOR alerts_owner FROM %I', v_me);
END $$;

-- POST-CONDITION, ASSERTED. A comment is not a proof: if the REVOKE above ever fails to bite --
-- a second membership row with a different grantor, a future PostgreSQL changing the rules --
-- this migration ABORTS rather than committing a standing privilege nobody approved. Checked for
-- every role the migration creates, not just alerts_owner.
DO $$
DECLARE v_me text := current_user; v_bad text;
BEGIN
  SELECT string_agg(r.rolname || '(set=' || m.set_option || ',inherit=' || m.inherit_option || ')',
                    ', ' ORDER BY r.rolname)
    INTO v_bad
    FROM pg_auth_members m
    JOIN pg_roles r ON r.oid = m.roleid
    JOIN pg_roles g ON g.oid = m.member
   WHERE g.rolname = v_me
     AND r.rolname IN ('alerts_owner','alerts_writer','alerts_dispatcher',
                       'alerts_reconciler','alerts_retention','alerts_audit')
     AND (m.set_option OR m.inherit_option);
  IF v_bad IS NOT NULL THEN
    RAISE EXCEPTION 'ALERTS_MIGRATOR_MEMBERSHIP_RESIDUAL (%)', v_bad USING ERRCODE = '42501';
  END IF;
END $$;

COMMIT;
