-- ============================================================================
-- FINMENTOR NEW LEAD ALERT OUTBOX - rollback (doc section 5)
-- SOURCE OF TRUTH: docs/NEW_LEAD_ALERT_OUTBOX_DDL_REVIEW.md
-- This file is a VERBATIM materialisation of the SQL fences in that document.
-- Generated by db/validation/extract-migration.mjs -- do not hand-edit.
-- ============================================================================
-- NOT APPLIED TO PRODUCTION. Proven on a disposable non-production cluster (§16): drops only
-- what the forward migration created, and it never touches public.*.
BEGIN;

-- AMENDMENT 2.3-A (real-Postgres proof, gate E12 of the 0002 suite). A later migration grants
-- these groups to runtime LOGIN roles, and DROP ROLE removes a membership SILENTLY. Measured:
-- with alerts_writer_rt and alerts_dispatcher_rt present, this rollback SUCCEEDED and left them
-- behind -- two logins, each with whatever password the owner had set, now members of nothing,
-- pointing at a schema that no longer exists. Nothing failed and nothing said so.
-- Rollback ORDER is therefore not a convention to be written in a runbook. It is checked here,
-- before anything is dropped.
DO $$
DECLARE v_rt text;
BEGIN
  SELECT string_agg(rolname, ', ' ORDER BY rolname) INTO v_rt
    FROM pg_roles WHERE rolname LIKE 'alerts\_%\_rt';
  IF v_rt IS NOT NULL THEN
    RAISE EXCEPTION 'ALERTS_ROLLBACK_RUNTIME_LOGIN_PRESENT (%) -- roll back 0002 first', v_rt
      USING ERRCODE = '2BP01';
  END IF;
END $$;

-- AMENDMENT 2.2-A. The forward migration ends by handing the migrator's working membership back
-- (§4.7), so at this point the migrator holds ADMIN OPTION on alerts_owner and nothing else: no
-- SET, no INHERIT, and therefore not even USAGE on the alerts schema. Every DROP below needs
-- them. The membership is taken back for the length of this rollback and destroyed with the role
-- at the end -- and because the whole rollback is ONE transaction, a failure anywhere undoes this
-- grant too. Named options, for the reason given in §4.1: a bare GRANT would not update the
-- existing membership row and every DROP would fail 42501.
DO $$ BEGIN
  EXECUTE format('GRANT alerts_owner TO %I WITH INHERIT TRUE', current_user);
  EXECUTE format('GRANT alerts_owner TO %I WITH SET TRUE',     current_user);
END $$;

DROP VIEW IF EXISTS alerts.new_lead_delivery_audit;
DROP VIEW IF EXISTS alerts.new_lead_outbox_audit;

DROP FUNCTION IF EXISTS alerts.purge_new_lead_keys();
DROP FUNCTION IF EXISTS alerts.purge_new_lead_deliveries();
DROP FUNCTION IF EXISTS alerts.purge_new_lead_payloads();
DROP FUNCTION IF EXISTS alerts.repair_new_lead_deliveries(text);
DROP FUNCTION IF EXISTS alerts.new_lead_events_present(text[]);
DROP FUNCTION IF EXISTS alerts.new_lead_attention();
DROP FUNCTION IF EXISTS alerts.expire_stale_claims(interval);
DROP FUNCTION IF EXISTS alerts.finalise_new_lead_delivery(text,text,uuid,text,text,text,interval);
DROP FUNCTION IF EXISTS alerts.claim_new_lead_delivery(text,integer);
DROP FUNCTION IF EXISTS alerts.enqueue_new_lead_b64(text,text,text,timestamptz,text);
DROP FUNCTION IF EXISTS alerts.enqueue_new_lead(text,text,text,timestamptz,jsonb);

DROP TRIGGER IF EXISTS new_lead_delivery_touch ON alerts.new_lead_delivery;
DROP TABLE   IF EXISTS alerts.new_lead_delivery;
DROP TABLE   IF EXISTS alerts.new_lead_outbox;
DROP TABLE   IF EXISTS alerts.retention_policy;
DROP FUNCTION IF EXISTS alerts.request_fingerprint(text);
DROP FUNCTION IF EXISTS alerts.touch_updated_at();

DROP SCHEMA IF EXISTS alerts;          -- deliberately NOT CASCADE: refuses if anything survives

-- Roles last. DROP OWNED clears the privileges they were granted; they own nothing, because
-- everything was owned by alerts_owner and has just been dropped.
--
-- AMENDMENT 2.1-D (real-Postgres proof, §16). DROP OWNED BY requires the PRIVILEGES of the role,
-- and the membership PostgreSQL hands a CREATEROLE migrator automatically carries neither SET
-- nor INHERIT (see 2.1-A). Revision 2 also REVOKED alerts_owner from the migrator immediately
-- BEFORE calling DROP OWNED BY on it. Both failed with 42501 "permission denied to drop
-- objects" for any non-superuser migrator. GRANT first; DROP ROLE removes the membership by
-- itself, so the REVOKE was never needed.
DO $$
DECLARE r text;
BEGIN
  FOREACH r IN ARRAY ARRAY['alerts_writer','alerts_dispatcher','alerts_reconciler',
                           'alerts_retention','alerts_audit'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
      EXECUTE format('GRANT %I TO %I WITH INHERIT TRUE', r, current_user);
      EXECUTE format('DROP OWNED BY %I', r);
      EXECUTE format('DROP ROLE %I', r);
    END IF;
  END LOOP;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'alerts_owner') THEN
    EXECUTE format('GRANT alerts_owner TO %I WITH INHERIT TRUE', current_user);
    EXECUTE 'DROP OWNED BY alerts_owner';
    EXECUTE 'DROP ROLE alerts_owner';
  END IF;
END $$;

-- POST-CONDITION, ASSERTED (AMENDMENT 2.2-E, owner decision). The block above GRANTs itself the
-- membership PostgreSQL requires for DROP OWNED BY, and DROP ROLE then destroys the membership
-- along with the role. That is the ONLY reason the temporary grant does not outlive the rollback,
-- and "the only reason" is exactly the kind of thing that stops being true after an edit. So it
-- is checked, not narrated: if any alerts_* role survives, the migrator may still be holding a
-- membership in it, and this rollback ABORTS -- which, being one transaction, also undoes the
-- temporary GRANT it made. Rollback either completes with no role and no membership, or changes
-- nothing at all.
DO $$
DECLARE v_left text;
BEGIN
  SELECT string_agg(rolname, ', ' ORDER BY rolname) INTO v_left
    FROM pg_roles
   WHERE rolname IN ('alerts_owner','alerts_writer','alerts_dispatcher',
                     'alerts_reconciler','alerts_retention','alerts_audit');
  IF v_left IS NOT NULL THEN
    RAISE EXCEPTION 'ALERTS_ROLLBACK_ROLE_RESIDUAL (%)', v_left USING ERRCODE = '42501';
  END IF;
END $$;

COMMIT;
