-- ============================================================================
-- FINMENTOR ALERTS RUNTIME LOGINS - rollback (doc section 2.7)
-- SOURCE OF TRUTH: docs/TELEGRAM_DURABLE_NEW_LEAD_DELIVERY_PLAN.md
-- This file is a VERBATIM materialisation of the SQL fences in that document.
-- Generated by db/validation/extract-migration.mjs -- do not hand-edit.
-- ============================================================================
-- ============================================================================
-- FINMENTOR — ALERTS RUNTIME LOGINS            rollback
-- Removes ONLY the two runtime logins. The alerts_* GROUP roles, the alerts schema and
-- everything in it belong to 0001 and are left exactly as they were.
-- ORDERING: run this BEFORE 0001's rollback. See §2.8.
-- ============================================================================
BEGIN;

DO $rb$
DECLARE r text;
BEGIN
  FOREACH r IN ARRAY ARRAY['alerts_writer_rt','alerts_dispatcher_rt'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
      -- These logins own nothing and hold no direct privilege -- but "nothing" is a claim, and
      -- DROP OWNED BY is the only statement that makes it true rather than asserted. It needs
      -- the PRIVILEGES of the role: 0001's amendment 2.1-D, where a CREATEROLE migrator's
      -- automatic membership carried neither SET nor INHERIT and every DROP OWNED BY failed
      -- 42501. The grant lives for the length of this transaction; DROP ROLE destroys it.
      EXECUTE format('GRANT %I TO %I WITH INHERIT TRUE', r, current_user);
      EXECUTE format('DROP OWNED BY %I', r);
      EXECUTE format('DROP ROLE %I', r);
    END IF;
  END LOOP;
END $rb$;

-- POST-CONDITION, ASSERTED. Same reasoning as 0001's rollback: the temporary membership above
-- is destroyed only as a side effect of DROP ROLE, and "only as a side effect" is exactly what
-- stops being true after an edit. If either login survives, this rollback ABORTS -- and being
-- one transaction, that also undoes the grant it just made to itself.
DO $rb$
DECLARE v_left text;
BEGIN
  SELECT string_agg(rolname, ', ' ORDER BY rolname) INTO v_left
    FROM pg_roles WHERE rolname IN ('alerts_writer_rt','alerts_dispatcher_rt');
  IF v_left IS NOT NULL THEN
    RAISE EXCEPTION 'ALERTS_RT_ROLLBACK_RESIDUAL (%)', v_left USING ERRCODE = '42501';
  END IF;

  -- And it must not have taken 0001 with it.
  IF (SELECT count(*) FROM pg_roles WHERE rolname IN
       ('alerts_owner','alerts_writer','alerts_dispatcher',
        'alerts_reconciler','alerts_retention','alerts_audit')) <> 6 THEN
    RAISE EXCEPTION 'ALERTS_RT_ROLLBACK_DAMAGED_0001' USING ERRCODE = '42501';
  END IF;
END $rb$;

COMMIT;
