-- ============================================================================
-- FINMENTOR ALERTS RUNTIME LOGINS - forward migration (doc sections 2.3-2.4)
-- SOURCE OF TRUTH: docs/TELEGRAM_DURABLE_NEW_LEAD_DELIVERY_PLAN.md
-- This file is a VERBATIM materialisation of the SQL fences in that document.
-- Generated by db/validation/extract-migration.mjs -- do not hand-edit.
-- ============================================================================
-- ============================================================================
-- FINMENTOR — ALERTS RUNTIME LOGINS            forward migration
-- PRECONDITION: 0001_new_lead_alert_outbox is applied, and §8 of
-- NEW_LEAD_ALERT_OUTBOX_PRODUCTION_APPLY.md holds. This file carries NO password:
-- the logins it creates exist and CANNOT AUTHENTICATE until the owner sets one.
-- ============================================================================
BEGIN;

-- Which logins THIS run created. "the password is still NULL" is a post-condition only for a
-- login the owner has not armed yet; asserting it unconditionally would make the migration
-- un-re-runnable the moment the credential goes live. ON COMMIT DROP: nothing survives.
CREATE TEMP TABLE alerts_rt_created (login name PRIMARY KEY) ON COMMIT DROP;

DO $mig$
DECLARE r record;
BEGIN
  FOR r IN SELECT * FROM (VALUES
      ('alerts_writer_rt',     'alerts_writer'),
      ('alerts_dispatcher_rt', 'alerts_dispatcher')) AS v(login, grp)
  LOOP
    -- 0001 must already be applied. A login created for a group that does not exist would be a
    -- credential with no privileges and no explanation.
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r.grp) THEN
      RAISE EXCEPTION 'ALERTS_RT_GROUP_MISSING (%)', r.grp USING ERRCODE = '42704';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r.login) THEN
      EXECUTE format('CREATE ROLE %I LOGIN NOINHERIT NOSUPERUSER NOBYPASSRLS NOCREATEDB '
                     'NOCREATEROLE NOREPLICATION PASSWORD NULL', r.login);
      INSERT INTO alerts_rt_created VALUES (r.login);
    END IF;

    -- BEFORE the role can ever authenticate. Not afterwards. PASSWORD NULL is written by the
    -- CREATE above and NOWHERE ELSE: a re-run must never wipe the password the owner has set.
    EXECUTE format('ALTER ROLE %I SET statement_timeout = %L', r.login, '8s');
    EXECUTE format('ALTER ROLE %I SET lock_timeout      = %L', r.login, '5s');
    EXECUTE format('ALTER ROLE %I SET search_path       = %L', r.login, 'pg_catalog');

    -- INHERIT TRUE is what makes EXECUTE usable without SET ROLE. SET FALSE stops the login
    -- assuming the group and acting outside its own audit identity.
    -- TWO STATEMENTS, ONE OPTION EACH -- see note 2 below. This is not a style choice.
    EXECUTE format('GRANT %I TO %I WITH INHERIT TRUE', r.grp, r.login);
    EXECUTE format('GRANT %I TO %I WITH SET FALSE',    r.grp, r.login);

    -- A CREATEROLE migrator is auto-granted membership in every role it creates. Under the
    -- default `createrole_self_grant` that grant carries ADMIN only -- but the GUC exists, and
    -- where it is set the migrator would quietly keep the ability to BECOME the credential.
    -- Conditional, because REVOKE ... OPTION FOR on an absent membership only warns, and a
    -- migration that emits warnings on every clean run teaches everyone to ignore them.
    IF EXISTS (SELECT 1 FROM pg_auth_members m
                 JOIN pg_roles t ON t.oid = m.roleid
                 JOIN pg_roles g ON g.oid = m.member
                WHERE t.rolname = r.login AND g.rolname = current_user
                  AND (m.set_option OR m.inherit_option)) THEN
      EXECUTE format('REVOKE SET OPTION FOR %I FROM %I',     r.login, current_user);
      EXECUTE format('REVOKE INHERIT OPTION FOR %I FROM %I', r.login, current_user);
    END IF;
  END LOOP;
END $mig$;

DO $chk$
DECLARE
  r        record;
  v_bad    text := '';
  v_alerts oid  := (SELECT oid FROM pg_namespace WHERE nspname = 'alerts');
BEGIN
  IF v_alerts IS NULL THEN
    RAISE EXCEPTION 'ALERTS_RT_SCHEMA_MISSING' USING ERRCODE = '3F000';
  END IF;

  FOR r IN SELECT * FROM (VALUES
      ('alerts_writer_rt',     'alerts_writer'),
      ('alerts_dispatcher_rt', 'alerts_dispatcher')) AS v(login, grp)
  LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_roles
                    WHERE rolname = r.login AND rolcanlogin AND NOT rolinherit AND NOT rolsuper
                      AND NOT rolbypassrls AND NOT rolcreaterole AND NOT rolcreatedb
                      AND NOT rolreplication) THEN
      v_bad := v_bad || format(' %s:attributes', r.login);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r.login
                     AND rolconfig @> ARRAY['statement_timeout=8s','lock_timeout=5s']) THEN
      v_bad := v_bad || format(' %s:rolconfig', r.login);
    END IF;

    -- Only for a login this run created (see the TEMP TABLE above). Where pg_authid is not
    -- readable the check is NOTICEd as skipped rather than silently counted as a pass.
    IF EXISTS (SELECT 1 FROM alerts_rt_created c WHERE c.login = r.login) THEN
      IF has_table_privilege(current_user, 'pg_authid', 'SELECT') THEN
        IF EXISTS (SELECT 1 FROM pg_authid WHERE rolname = r.login AND rolpassword IS NOT NULL) THEN
          v_bad := v_bad || format(' %s:password_not_null', r.login);
        END IF;
      ELSE
        RAISE NOTICE 'ALERTS_RT_PASSWORD_CHECK_SKIPPED (%): pg_authid is not readable by %',
                     r.login, current_user;
      END IF;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_auth_members m
                     JOIN pg_roles t ON t.oid = m.roleid
                     JOIN pg_roles g ON g.oid = m.member
                    WHERE g.rolname = r.login AND t.rolname = r.grp
                      AND m.inherit_option AND NOT m.set_option) THEN
      v_bad := v_bad || format(' %s:own_membership', r.login);
    END IF;

    IF (SELECT count(*) FROM pg_auth_members m JOIN pg_roles g ON g.oid = m.member
         WHERE g.rolname = r.login) <> 1 THEN
      v_bad := v_bad || format(' %s:extra_membership', r.login);
    END IF;

    IF NOT has_schema_privilege(r.login, v_alerts, 'USAGE') THEN
      v_bad := v_bad || format(' %s:no_schema_usage', r.login);
    END IF;
    IF has_schema_privilege(r.login, v_alerts, 'CREATE') THEN
      v_bad := v_bad || format(' %s:schema_create', r.login);
    END IF;
  END LOOP;

  -- EXECUTE, both ways round: what each login must be able to call, and what it must not.
  -- `n` guards the assumption the name lookup rests on: if an overload is ever added, the
  -- matrix would quietly check only one of them, so it fails instead.
  FOR r IN
    SELECT l.login, v.proname, p.oid AS fnoid, (v.holder = l.login) AS expected,
           (SELECT count(*) FROM pg_proc x
             WHERE x.pronamespace = v_alerts AND x.proname = v.proname) AS n
      FROM (VALUES ('alerts_writer_rt'), ('alerts_dispatcher_rt')) AS l(login)
      CROSS JOIN (VALUES
        ('enqueue_new_lead',            'alerts_writer_rt'),
        ('enqueue_new_lead_b64',        'alerts_writer_rt'),
        ('claim_new_lead_delivery',     'alerts_dispatcher_rt'),
        ('finalise_new_lead_delivery',  'alerts_dispatcher_rt'),
        ('expire_stale_claims',         'alerts_dispatcher_rt'),
        ('new_lead_attention',          'alerts_dispatcher_rt'),
        ('request_fingerprint',         '-'),
        ('new_lead_events_present',     '-'),
        ('repair_new_lead_deliveries',  '-'),
        ('purge_new_lead_payloads',     '-'),
        ('purge_new_lead_deliveries',   '-'),
        ('purge_new_lead_keys',         '-')) AS v(proname, holder)
      LEFT JOIN pg_proc p ON p.pronamespace = v_alerts AND p.proname = v.proname
  LOOP
    IF r.n <> 1 THEN
      v_bad := v_bad || format(' alerts.%s:resolves_to_%s', r.proname, r.n);
    ELSIF has_function_privilege(r.login, r.fnoid, 'EXECUTE') <> r.expected THEN
      v_bad := v_bad || format(' %s:EXECUTE(%s)<>%s', r.login, r.proname, r.expected);
    END IF;
  END LOOP;

  -- No table privilege anywhere in the schema, on any relation, by any verb.
  FOR r IN
    SELECT l.login, t.relname, c.oid AS reloid, p.priv
      FROM (VALUES ('alerts_writer_rt'), ('alerts_dispatcher_rt')) AS l(login)
      CROSS JOIN (VALUES ('new_lead_outbox'), ('new_lead_delivery'), ('retention_policy'),
                         ('new_lead_outbox_audit'), ('new_lead_delivery_audit')) AS t(relname)
      CROSS JOIN (VALUES ('SELECT'), ('INSERT'), ('UPDATE'), ('DELETE')) AS p(priv)
      LEFT JOIN pg_class c ON c.relnamespace = v_alerts AND c.relname = t.relname
  LOOP
    IF r.reloid IS NULL THEN
      v_bad := v_bad || format(' alerts.%s:missing', r.relname);
    ELSIF has_table_privilege(r.login, r.reloid, r.priv) THEN
      v_bad := v_bad || format(' %s:%s_ON_%s', r.login, r.priv, r.relname);
    END IF;
  END LOOP;

  -- G5 is a different system. Neither login may reach its ledger, by any verb. The join is the
  -- guard: where G5 is absent there is nothing to prove and the loop simply does not run.
  FOR r IN
    SELECT l.login, p.priv, c.oid AS reloid
      FROM (VALUES ('alerts_writer_rt'), ('alerts_dispatcher_rt')) AS l(login)
      CROSS JOIN (VALUES ('SELECT'), ('INSERT'), ('UPDATE'), ('DELETE')) AS p(priv)
      JOIN pg_class c ON c.relname = 'telegram_initdata_replays'
      JOIN pg_namespace g5 ON g5.oid = c.relnamespace AND g5.nspname = 'public'
  LOOP
    IF has_table_privilege(r.login, r.reloid, r.priv) THEN
      v_bad := v_bad || format(' %s:G5_%s', r.login, r.priv);
    END IF;
  END LOOP;

  -- Nobody -- not the migrator, not a leftover grant -- may BECOME either login or inherit its
  -- privileges. A credential another role can assume is not a credential.
  IF EXISTS (SELECT 1 FROM pg_auth_members m JOIN pg_roles t ON t.oid = m.roleid
              WHERE t.rolname IN ('alerts_writer_rt','alerts_dispatcher_rt')
                AND (m.set_option OR m.inherit_option)) THEN
    v_bad := v_bad || ' any_role:set_or_inherit_on_a_runtime_login';
  END IF;

  IF v_bad <> '' THEN
    RAISE EXCEPTION 'ALERTS_RT_POSTCONDITION_FAILED (%)', v_bad USING ERRCODE = '42501';
  END IF;
END $chk$;

COMMIT;
