-- ============================================================================
-- FINMENTOR ALERTS WRITER RELAY LOGIN - rollback (doc section 8.2)
-- SOURCE OF TRUTH: docs/TELEGRAM_DURABLE_NEW_LEAD_DELIVERY_PLAN.md
-- This file is a VERBATIM materialisation of the SQL fences in that document.
-- Generated by db/validation/extract-migration.mjs -- do not hand-edit.
-- ============================================================================
-- ============================================================================
-- FINMENTOR — ALERTS WRITER RELAY LOGIN         rollback
-- Removes ONLY alerts_writer_relay_rt. 0001 and 0002 objects are untouched.
-- ORDERING: run this BEFORE 0001's rollback, which refuses while any
-- alerts_*_rt login exists (0001 amendment 2.3-A covers this name too).
-- ============================================================================
BEGIN;

-- The state this rollback promises not to disturb, captured BEFORE it acts. "we only dropped
-- the relay" is otherwise a claim; here it is compared.
CREATE TEMP TABLE alerts_relay_pre ON COMMIT DROP AS
  SELECT rolname FROM pg_roles
   WHERE rolname IN ('alerts_owner','alerts_writer','alerts_dispatcher','alerts_reconciler',
                     'alerts_retention','alerts_audit','alerts_writer_rt','alerts_dispatcher_rt');

DO $rb$
DECLARE r text := 'alerts_writer_relay_rt';
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
    -- DROP OWNED BY needs the PRIVILEGES of the role (0001 amendment 2.1-D). The grant lives
    -- for the length of this transaction; DROP ROLE destroys it.
    EXECUTE format('GRANT %I TO %I WITH INHERIT TRUE', r, current_user);
    EXECUTE format('DROP OWNED BY %I', r);
    EXECUTE format('DROP ROLE %I', r);
  END IF;
END $rb$;

DO $rb$
DECLARE v_missing text;
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'alerts_writer_relay_rt') THEN
    RAISE EXCEPTION 'ALERTS_RELAY_ROLLBACK_RESIDUAL' USING ERRCODE = '42501';
  END IF;

  -- Everything that existed before must still exist: the six group roles AND, if 0002 is
  -- applied, both n8n runtime logins. A rollback that quietly took a neighbour with it is
  -- the same class of defect as 0001 amendment 2.3-A.
  SELECT string_agg(p.rolname, ', ' ORDER BY p.rolname) INTO v_missing
    FROM alerts_relay_pre p
   WHERE NOT EXISTS (SELECT 1 FROM pg_roles x WHERE x.rolname = p.rolname);
  IF v_missing IS NOT NULL THEN
    RAISE EXCEPTION 'ALERTS_RELAY_ROLLBACK_DAMAGED_NEIGHBOURS (%)', v_missing USING ERRCODE = '42501';
  END IF;
END $rb$;

COMMIT;
