/* FINMENTOR B.2 Mini App prototype — mock-only, zero backend writes */
(function(){'use strict';
var tg=window.Telegram&&window.Telegram.WebApp?window.Telegram.WebApp:null;
var main=document.getElementById('main'),progress=document.getElementById('progress'),progressBar=document.getElementById('progressBar'),backBtn=document.getElementById('backBtn'),brandHome=document.getElementById('brandHome'),secureChip=document.getElementById('secureChip'),secureChipText=document.getElementById('secureChipText');
var screens=['entry','profile','control','priority','preview','contact','consent','submitted'],stepIndex=0;
var state={sector:'',turnover:'',cash:'',profit:'',treasury:'',kpi:'',pain:'',urgency:'',context:'',contact_name:'',company:'',direct:'',consent:''};
function safe(fn){try{fn()}catch(e){if(window.console)console.warn('[FINMENTOR miniapp]',e)}}
safe(function(){if(tg){tg.ready();tg.expand();if(tg.setHeaderColor)tg.setHeaderColor('#08111F');if(tg.setBackgroundColor)tg.setBackgroundColor('#08111F')}});
function tgUser(){return tg&&tg.initDataUnsafe&&tg.initDataUnsafe.user?tg.initDataUnsafe.user:null}
function inTelegram(){return !!(tg&&tgUser())}
function template(name){var tpl=document.getElementById('tpl-'+name);return tpl?tpl.content.cloneNode(true):document.createTextNode('')}
function render(name){stepIndex=Math.max(0,screens.indexOf(name));main.replaceChildren(template(name));updateProgress();backBtn.hidden=name==='entry'||name==='submitted';wire(name);var reduced=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;window.scrollTo({top:0,behavior:reduced?'auto':'smooth'})}
function updateProgress(){var pct=stepIndex===0?0:Math.min(100,Math.round((stepIndex/(screens.length-2))*100));progressBar.style.width=pct+'%';progress.setAttribute('aria-valuenow',String(pct))}
function selectSingle(container,value){Array.prototype.forEach.call(container.querySelectorAll('[data-value]'),function(el){var selected=el.getAttribute('data-value')===value;el.classList.toggle('is-selected',selected);el.setAttribute('aria-pressed',selected?'true':'false')})}
function bindChoiceGroups(root,onChange){Array.prototype.forEach.call(root.querySelectorAll('[data-field]'),function(group){var field=group.getAttribute('data-field');Array.prototype.forEach.call(group.querySelectorAll('[data-value]'),function(btn){btn.setAttribute('aria-pressed','false');btn.addEventListener('click',function(){state[field]=btn.getAttribute('data-value');selectSingle(group,state[field]);if(onChange)onChange()})});if(state[field])selectSingle(group,state[field])})}
function openUrl(relative){var url=new URL(relative,window.location.href).href;if(tg&&tg.openLink)tg.openLink(url);else window.open(url,'_blank','noopener')}
function wire(name){var root=main,nextBtn;
if(name==='entry'){renderTelegramContext();var start=root.querySelector('[data-action="start"]');if(hasProgress())start.textContent='Продолжить диагностику';start.addEventListener('click',function(){render(firstIncompleteScreen())});root.querySelector('[data-action="website"]').addEventListener('click',function(){openUrl('../')});return}
if(name==='profile'){nextBtn=root.querySelector('[data-action="next"]');function validate(){nextBtn.disabled=!(state.sector&&state.turnover)}bindChoiceGroups(root,validate);validate();nextBtn.addEventListener('click',function(){render('control')});return}
if(name==='control'){nextBtn=root.querySelector('[data-action="next"]');function validate(){nextBtn.disabled=!(state.cash&&state.profit&&state.treasury&&state.kpi)}bindChoiceGroups(root,validate);validate();nextBtn.addEventListener('click',function(){render('priority')});return}
if(name==='priority'){var previewBtn=root.querySelector('[data-action="preview"]'),contextText=root.querySelector('#contextText');contextText.value=state.context||'';contextText.addEventListener('input',function(){state.context=contextText.value.trim()});function validate(){previewBtn.disabled=!(state.pain&&state.urgency)}bindChoiceGroups(root,validate);validate();previewBtn.addEventListener('click',function(){render('preview')});return}
if(name==='preview'){paintResult(root);root.querySelector('[data-action="contact"]').addEventListener('click',function(){render('contact')});root.querySelector('[data-action="restart"]').addEventListener('click',function(){resetState();render('entry')});return}
if(name==='contact'){var nameInput=root.querySelector('#contactName'),companyInput=root.querySelector('#contactCompany'),directInput=root.querySelector('#contactDirect'),directHint=root.querySelector('#directHint'),consentBtn=root.querySelector('[data-action="consent"]'),user=tgUser();if(!state.contact_name&&user&&user.first_name)state.contact_name=user.first_name;nameInput.value=state.contact_name||'';companyInput.value=state.company||'';directInput.value=state.direct||'';directInput.placeholder=inTelegram()?'Необязательно в Telegram':'Телефон или email';directHint.textContent=inTelegram()?'Telegram может быть основным каналом обратной связи.':'Вне Telegram нужен прямой контакт для обратной связи.';function validate(){state.contact_name=nameInput.value.trim();state.company=companyInput.value.trim();state.direct=directInput.value.trim();consentBtn.disabled=!(state.contact_name&&state.company&&(inTelegram()||state.direct))}[nameInput,companyInput,directInput].forEach(function(el){el.addEventListener('input',validate)});validate();consentBtn.addEventListener('click',function(){render('consent')});return}
if(name==='consent'){paintConsent(root);root.querySelector('[data-action="submit-yes"]').addEventListener('click',function(){state.consent='yes';render('submitted');var title=main.querySelector('#submitTitle'),text=main.querySelector('#submitText');if(title)title.textContent='Прототип: запрос готов к передаче';if(text)text.textContent='B.2.0 не вызывает backend. В рабочей версии этот экран откроется только после canonical ok:true от Lead Intake.'});root.querySelector('[data-action="submit-no"]').addEventListener('click',function(){state.consent='no';render('submitted');var title=main.querySelector('#submitTitle'),text=main.querySelector('#submitText');if(title)title.textContent='Ничего не передано';if(text)text.textContent='Без вашего согласия FINMENTOR не отправляет диагностический контекст эксперту. Можно вернуться позже.'});return}
if(name==='submitted'){bindPostActions(root);return}}
function renderTelegramContext(){var el=main.querySelector('#telegramContext'),user=tgUser();if(!el)return;if(inTelegram()){el.classList.add('is-ok');el.textContent='Telegram-контекст доступен · '+(user.first_name||'пользователь')+'. В B.2.0 он используется только для интерфейса и не отправляется на backend.';secureChip.classList.add('is-telegram');secureChipText.textContent='Telegram'}else{el.textContent='Предпросмотр вне Telegram. Интерфейс работает, но Telegram-идентификация будет доступна только внутри Mini App.';secureChip.classList.remove('is-telegram');secureChipText.textContent='Preview'}}
function paintConsent(root){var text=root.querySelector('#consentText'),summary=root.querySelector('#consentSummary');text.textContent=inTelegram()?'Будут переданы ответы диагностики, указанные контактные данные и Telegram-контекст, необходимый для обратной связи.':'Будут переданы ответы диагностики и указанные контактные данные. Telegram-контекст отсутствует.';var sectorMap={retail:'Торговля',services:'Услуги',production:'Производство',real_estate:'Недвижимость',ecommerce:'E-commerce',other:'Другое'},turnoverMap={lt100k:'до 100k EUR','100k_500k':'100k–500k EUR','500k_2m':'500k–2M EUR','2m_10m':'2M–10M EUR',gt10m:'10M+ EUR'},urgencyMap={now:'Сейчас',month:'В течение месяца',quarter:'В течение квартала',none:'Нет срочности'};summary.innerHTML='<div class="consent-summary__row"><span>Компания</span><b>'+escapeHtml(state.company||'—')+'</b></div><div class="consent-summary__row"><span>Профиль</span><b>'+escapeHtml((sectorMap[state.sector]||'—')+' · '+(turnoverMap[state.turnover]||'—'))+'</b></div><div class="consent-summary__row"><span>Горизонт</span><b>'+escapeHtml(urgencyMap[state.urgency]||'—')+'</b></div>'}
function bindPostActions(root){var closeBtn=root.querySelector('[data-action="close"]');root.querySelector('[data-action="materials"]').addEventListener('click',function(){openUrl('../materials.html')});root.querySelector('[data-action="services"]').addEventListener('click',function(){openUrl('../#solutions')});root.querySelector('[data-action="website"]').addEventListener('click',function(){openUrl('../')});if(closeBtn)closeBtn.addEventListener('click',function(){if(tg&&tg.close)tg.close();else render('entry')})}
function paintResult(root){var focus=root.querySelector('#resultFocus'),summary=root.querySelector('#resultSummary'),grid=root.querySelector('#insightGrid'),nextTitle=root.querySelector('#nextStepTitle'),nextText=root.querySelector('#nextStepText'),weak=['cash','profit','treasury','kpi'].filter(function(k){return state[k]==='unclear'}),partial=['cash','profit','treasury','kpi'].filter(function(k){return state[k]==='partial'}),map={cash:'Деньги / Cash Flow',profit:'Прибыль / P&L',treasury:'Казначейство',kpi:'KPI и контроль'},primary=weak[0]||partial[0]||'kpi';focus.textContent=map[primary]||'Финансовый контроль';if(weak.length>=2)summary.textContent='Несколько ключевых контуров управления сейчас требуют ручной проверки. Главный риск — решения принимаются быстрее, чем появляется единая финансовая картина.';else if(weak.length===1)summary.textContent='В целом система уже частично сформирована, но один критический контур остаётся непрозрачным для регулярных управленческих решений.';else summary.textContent='Базовый финансовый контроль выглядит зрелее среднего, но предварительная диагностика не подтверждает качество цифр и процессов без проверки данных.';var observations=[];if(state.cash==='unclear')observations.push(['Cash visibility','Нет устойчивой видимости движения денег.']);if(state.profit==='unclear')observations.push(['Profit visibility','P&L не даёт собственнику понятной картины прибыли.']);if(state.treasury==='unclear')observations.push(['Treasury','Платёжный процесс воспринимается как несистемный.']);if(state.kpi==='unclear')observations.push(['Management control','KPI и управленческий контроль не собраны в работающий контур.']);if(!observations.length)observations.push(['Control maturity','Критического разрыва по ответам не видно; нужна проверка качества данных.']);if(state.urgency==='none')observations.push(['Urgency','Вы указали, что срочности нет — это не повышает приоритет заявки.']);grid.innerHTML=observations.slice(0,3).map(function(x){return '<div class="insight"><span>'+escapeHtml(x[0])+'</span><b>'+escapeHtml(x[1])+'</b></div>'}).join('');if(weak.length>=2||state.urgency==='now'){nextTitle.textContent='Financial X-Ray';nextText.textContent='Сначала подтвердить причины разрывов на фактических данных и определить 3–5 управленческих приоритетов.'}else{nextTitle.textContent='Discovery Call';nextText.textContent='Коротко сверить контекст и решить, нужна ли глубокая диагностика или достаточно точечной настройки процесса.'}}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[c]})}
function resetState(){Object.keys(state).forEach(function(k){state[k]=''})}
function hasProgress(){return !!(state.sector||state.turnover||state.cash||state.pain||state.contact_name)}
function firstIncompleteScreen(){if(!(state.sector&&state.turnover))return'profile';if(!(state.cash&&state.profit&&state.treasury&&state.kpi))return'control';if(!(state.pain&&state.urgency))return'priority';return'preview'}
backBtn.addEventListener('click',function(){if(stepIndex<=1)render('entry');else render(screens[stepIndex-1])});brandHome.addEventListener('click',function(e){e.preventDefault();render('entry')});render('entry');
})();
