#!/usr/bin/env node
// FINMENTOR — the Premium Concierge candidate, EXECUTED.
//
//   node qa/premium-ux-concierge-candidate.test.mjs
//
// Offline. No tenant, no network, no credentials.
//
// WHY THIS GATE RUNS THE NODE INSTEAD OF READING IT. The candidate's node body is generated by
// scripts/build-premium-concierge.mjs, and that script's own checks are string matches: they can
// tell you the word `rotate` appears twice, not that a committed cycle survives a `/start`. A
// generated artifact that has never been executed is a guess with good punctuation.
//
// So this loads the candidate JSON, lifts `Build Bot Response` out of it, and runs it against a
// stub `$input` for each scenario that matters — including the ones that must NOT happen.

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { prepareConcierge, verifyPremiumStarts, CONCIERGE_ID } from '../scripts/deploy-final-p1.mjs';
import { splicePremiumSession } from '../scripts/deploy-c3-concierge-cycle.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const CANDIDATE = join(ROOT, 'n8n', 'candidate', 'premium-concierge-candidate.json');

let pass = 0;
const failures = [];
function check(name, fn) {
  try { fn(); pass++; console.log('  PASS  ' + name); }
  catch (e) { failures.push(name + ': ' + e.message); console.log('  FAIL  ' + name + ' -> ' + e.message); }
}
const assert = (c, m) => { if (!c) throw new Error(m); };
const eq = (a, b, m) => { if (a !== b) throw new Error(m + ' (got ' + JSON.stringify(a) + ', want ' + JSON.stringify(b) + ')'); };

const wf = JSON.parse(readFileSync(CANDIDATE, 'utf8'));
// The premium body lives on its OWN node now. `Build Bot Response` is the legacy node and must
// stay exactly as it is, because that is what every non-owner still runs.
const body = wf.nodes.find((n) => n.name === 'Build Bot Response').parameters.jsCode;

// The node reads `$input.first().json`. Everything else it touches is its own.
const runner = new Function('$input', body);
function run(src) { return runner({ first: () => ({ json: src }) })[0].json; }

const CHAT = '777000';
const CYCLE = 'CY-2026-08-29-abcdef';
const LEAD = 'LEAD-000123';

// A committed cycle: a lead exists AND belongs to this cycle.
const committed = (extra) => Object.assign({
  chat_id: CHAT, cycle_id: CYCLE, lead_id: LEAD, lead_cycle_id: CYCLE, state: 'TG_SUBMITTED'
}, extra || {});
// An unfinished draft: no lead, draft_state === 'draft'.
const drafting = (extra) => Object.assign({
  chat_id: CHAT, cycle_id: CYCLE, lead_id: '', lead_cycle_id: '', draft_state: 'draft',
  draft_step: 'objective', state: 'TG_ENTRY'
}, extra || {});
const fresh = (extra) => Object.assign({ chat_id: CHAT, cycle_id: CYCLE, state: 'TG_ENTRY' }, extra || {});

const A = {
  DESCRIBE: 'p|describe', BRIEF: 'p|brief', CONFIRM_OK: 'p|ctx_ok', CONFIRM_FIX: 'p|ctx_fix',
  OPEN: 'p|open', RESUME: 'p|resume', RESTART: 'p|restart', RESTART_CONFIRM: 'p|restart_y',
  APPEND: 'p|append', NEW: 'p|new', NEW_CONFIRM: 'p|new_y', BACK: 'p|back', RETRY: 'p|retry'
};

const QUALIFICATION = ['TG_ENTRY', 'TG_FREEFORM_PROBLEM', 'TG_CONFIRM_CONTEXT', 'TG_OPEN_BRIEF', 'TG_RESUME_DRAFT'];
const labels = (r) => (r.reply_markup.inline_keyboard || []).map((row) => row[0].text);

function finalCutoverFixture() {
  const live = JSON.parse(JSON.stringify(wf));
  live.id = CONCIERGE_ID;
  live.name = 'FINMENTOR Telegram Client Concierge PREMIUM AI GUARDED';
  live.active = true;
  live.versionId = 'fixture-version';
  live.staticData = { node: { keep: true } };
  const canonicalSession = live.nodes.find((n) => n.name === 'Get Bot Session');
  const canonicalResponse = live.nodes.find((n) => n.name === 'Build Bot Response');
  const premiumSession = JSON.parse(JSON.stringify(canonicalSession));
  premiumSession.id = 'fixture-premium-session';
  premiumSession.name = 'Get Bot Session (Premium)';
  premiumSession.parameters.jsCode = splicePremiumSession(canonicalSession.parameters.jsCode);
  const premiumResponse = JSON.parse(JSON.stringify(canonicalResponse));
  premiumResponse.id = 'fixture-premium-response';
  premiumResponse.name = 'Build Bot Response (Premium)';
  premiumResponse.parameters.jsCode = premiumResponse.parameters.jsCode
    .split('__PREMIUM_MINIAPP_URL__').join('https://app.finmentor.test/brief');
  live.nodes.push(
    { id: 'fixture-gate', name: 'Premium Owner Gate', type: 'n8n-nodes-base.if', typeVersion: 2, position: [0, 0], parameters: {} },
    { id: 'fixture-read', name: 'Read Cycle Commit', type: 'n8n-nodes-base.dataTable', typeVersion: 1.1, position: [0, 0], parameters: {} },
    { id: 'fixture-adopt', name: 'Adopt Cycle Commit', type: 'n8n-nodes-base.code', typeVersion: 2, position: [0, 0], parameters: { jsCode: 'return $input.all();' } },
    premiumSession,
    premiumResponse
  );
  live.connections['Find Session'] = { main: [[{ node: 'Premium Owner Gate', type: 'main', index: 0 }]] };
  live.connections['Premium Owner Gate'] = { main: [
    [{ node: 'Read Cycle Commit', type: 'main', index: 0 }],
    [{ node: 'Get Bot Session', type: 'main', index: 0 }]
  ] };
  live.connections['Read Cycle Commit'] = { main: [[{ node: 'Adopt Cycle Commit', type: 'main', index: 0 }]] };
  live.connections['Adopt Cycle Commit'] = { main: [[{ node: 'Get Bot Session (Premium)', type: 'main', index: 0 }]] };
  live.connections['Get Bot Session (Premium)'] = { main: [[{ node: 'Build Bot Response (Premium)', type: 'main', index: 0 }]] };
  live.connections['Build Bot Response (Premium)'] = { main: [[{ node: 'Build Transport Request', type: 'main', index: 0 }]] };
  return live;
}

console.log('Premium Concierge candidate — executed');
console.log('');

// ---------------------------------------------------------------- it runs at all

check('the generated node executes and returns the full output contract', () => {
  const r = run({ session: fresh(), message_text: '/start' });
  for (const k of ['chat_id', 'reply_text', 'reply_markup', 'tg_body', 'session',
                   'lead_ready', 'lead_payload', 'ai_guarded', 'debug', 'event']) {
    assert(Object.prototype.hasOwnProperty.call(r, k), 'missing output key: ' + k);
  }
  eq(r.chat_id, CHAT, 'chat_id');
  eq(r.tg_body.chat_id, CHAT, 'tg_body.chat_id');
  eq(r.tg_body.text, r.reply_text, 'tg_body.text must equal reply_text');
});

// ---------------------------------------------------------------- the three-way /start

check('/start on a fresh session shows the entry screen', () => {
  const r = run({ session: fresh(), message_text: '/start' });
  eq(r.debug.state_after, 'TG_ENTRY', 'state');
  eq(labels(r).join(' | '), 'Описать задачу | Подготовить бриф', 'entry actions');
});

check('/start, /start ru and /start ro all reach the locale-correct premium TG_ENTRY', () => {
  const cases = [
    ['/start', 'ru', 'Подготовка к первой встрече', ['Описать задачу', 'Подготовить бриф']],
    ['/start ru', 'ru', 'Подготовка к первой встрече', ['Описать задачу', 'Подготовить бриф']],
    ['/start ro', 'ro', 'Pregătirea primei întâlniri', ['Descrieți solicitarea', 'Pregătiți sinteza']]
  ];
  for (const [command, locale, subtitle, buttons] of cases) {
    const r = run({ session: fresh({ language: '' }), message_text: command });
    eq(r.debug.state_after, 'TG_ENTRY', command + ' state');
    eq(r.session.language, locale, command + ' locale');
    assert(r.reply_text.includes('<b>FINMENTOR</b>') && r.reply_text.includes(subtitle), command + ' premium entry copy');
    eq(JSON.stringify(labels(r)), JSON.stringify(buttons), command + ' entry actions');
    const visible = r.reply_text + '\n' + labels(r).join('\n');
    for (const legacy of ['Free Text Request', 'Продолжить диагностику', 'Оставить контакт']) {
      assert(!visible.includes(legacy), command + ' exposed legacy entry text: ' + legacy);
    }
  }
});

check('final P1 cutover promotes the accepted premium implementation and bypasses only the obsolete owner split', () => {
  const live = finalCutoverFixture();
  const before = JSON.stringify(live);
  const prepared = prepareConcierge(live, wf);
  eq(JSON.stringify(live), before, 'the live input was mutated');
  eq(JSON.stringify(prepared.changedNodes), JSON.stringify(['Build Bot Response', 'Get Bot Session']), 'changed nodes');
  eq(JSON.stringify(prepared.changedConnections), JSON.stringify(['Adopt Cycle Commit', 'Find Session']), 'changed connections');
  eq(prepared.candidate.connections['Find Session'].main[0][0].node, 'Read Cycle Commit', 'public entry skips the owner gate');
  eq(prepared.candidate.connections['Adopt Cycle Commit'].main[0][0].node, 'Get Bot Session', 'C3 adoption reaches the canonical session');
  eq(prepared.candidate.connections['Get Bot Session'].main[0][0].node, 'Build Bot Response', 'canonical premium response');
  eq(prepared.candidate.connections['Build Bot Response'].main[0][0].node, 'Build Transport Request', 'transport rejoin');
  eq(JSON.stringify(prepared.candidate.settings), JSON.stringify(live.settings), 'settings');
  eq(JSON.stringify(prepared.candidate.staticData), JSON.stringify(live.staticData), 'staticData');
  eq(verifyPremiumStarts(prepared.candidate).length, 3, 'start variants');
});

check('final P1 cutover refuses an unrecognised live route instead of splicing blindly', () => {
  const live = finalCutoverFixture();
  live.connections['Premium Owner Gate'].main[1] = [{ node: 'Build Bot Response', type: 'main', index: 0 }];
  let error = null;
  try { prepareConcierge(live, wf); } catch (caught) { error = caught; }
  assert(error && /expected/.test(error.message), 'unexpected live graph was accepted');
});

check('/start on an unfinished draft offers RESUME, not a fresh start', () => {
  const r = run({ session: drafting(), message_text: '/start' });
  eq(r.debug.state_after, 'TG_RESUME_DRAFT', 'state');
  eq(r.debug.rotate, false, 'a resume must not rotate');
  assert(/Продолжить/.test(r.reply_text) || labels(r).indexOf('Продолжить') !== -1,
    'the resume screen does not offer «Продолжить»');
});

check('/start on a COMMITTED cycle lands on the terminal screen — the defect this replaces', () => {
  const r = run({ session: committed(), message_text: '/start' });
  eq(r.debug.state_after, 'TG_SUBMITTED', 'state');
  eq(r.debug.rotate, false, 'the /start reset rotated a committed cycle');
  eq(r.session.lead_id, LEAD, 'the committed lead_id was destroyed by /start');
  eq(r.session.cycle_id, CYCLE, 'the cycle was rotated by /start');
});

check('/menu behaves exactly like /start', () => {
  const a = run({ session: committed(), message_text: '/menu' });
  eq(a.debug.state_after, 'TG_SUBMITTED', '/menu on committed');
  const b = run({ session: fresh(), message_text: '/menu' });
  eq(b.debug.state_after, 'TG_ENTRY', '/menu on fresh');
});

// ---------------------------------------------------------------- the terminal rule

check('NO input returns a committed cycle to qualification', () => {
  const inputs = [
    { message_text: '/start' }, { message_text: '/menu' }, { message_text: 'здравствуйте' },
    { message_text: 'хочу новый бриф' },
    ...Object.keys(A).filter((k) => k !== 'NEW_CONFIRM').map((k) => ({ callback_data: A[k] }))
  ];
  for (const i of inputs) {
    const r = run(Object.assign({ session: committed() }, i));
    assert(QUALIFICATION.indexOf(r.debug.state_after) === -1,
      'input ' + JSON.stringify(i) + ' reached qualification state ' + r.debug.state_after);
    eq(r.session.lead_id, LEAD, 'input ' + JSON.stringify(i) + ' destroyed the committed lead');
    eq(r.debug.rotate, false, 'input ' + JSON.stringify(i) + ' rotated the cycle');
  }
});

check('a stale inline button from an old message cannot rotate a committed cycle', () => {
  // The button that used to advance a draft, tapped after submission.
  for (const stale of [A.OPEN, A.RESUME, A.CONFIRM_OK, A.DESCRIBE, A.BRIEF, A.RESTART_CONFIRM]) {
    const r = run({ session: committed(), callback_data: stale });
    eq(r.debug.state_after, 'TG_SUBMITTED', 'stale ' + stale);
    eq(r.session.lead_id, LEAD, 'stale ' + stale + ' destroyed the lead');
  }
});

check('«Начать новый вопрос» asks first and rotates nothing', () => {
  const r = run({ session: committed(), callback_data: A.NEW });
  eq(r.debug.state_after, 'TG_NEW_REQUEST_CONFIRM', 'state');
  eq(r.debug.rotate, false, 'the unconfirmed tap rotated');
  eq(r.session.lead_id, LEAD, 'the unconfirmed tap destroyed the lead');
});

check('only the CONFIRMED new-request rotates, and it archives the lead', () => {
  const r = run({ session: committed(), callback_data: A.NEW_CONFIRM });
  eq(r.debug.rotate, true, 'the confirmed action did not rotate');
  eq(r.debug.state_after, 'TG_ENTRY', 'state after rotate');
  eq(r.session.archived_lead_id, LEAD, 'the lead was not archived — it was simply lost');
  eq(r.session.lead_id, '', 'lead_id was not cleared');
  eq(r.session.cycle_id, '', 'the new cycle must be minted by the issuer, not here');
});

check('a confirmed DISCARD of an uncommitted draft rotates but archives nothing', () => {
  const r = run({ session: drafting(), callback_data: A.RESTART_CONFIRM });
  eq(r.debug.rotate, true, 'the confirmed discard did not rotate');
  assert(!r.session.archived_lead_id, 'it archived a lead that never existed');
  eq(r.session.draft_state, '', 'the draft was not cleared');
});

check('«Начать заново» on a draft asks first', () => {
  const r = run({ session: drafting(), callback_data: A.RESTART });
  eq(r.debug.rotate, false, 'the unconfirmed discard rotated');
  eq(r.debug.state_after, 'TG_NEW_REQUEST_CONFIRM', 'state');
});

check('exactly two ACTIONS in the whole vocabulary can rotate a cycle', () => {
  // The invariant is about BRANCHES, not about state-input pairs. RESTART_CONFIRM reaches the same
  // single branch from a draft and from a session that has neither draft nor lead; counting those
  // as two findings measures the fixture, not the machine.
  const rotating = new Set();
  for (const sess of [committed, drafting, fresh]) {
    for (const k of Object.keys(A)) {
      if (run({ session: sess(), callback_data: A[k] }).debug.rotate === true) { rotating.add(k); }
    }
    for (const t of ['/start', '/menu', 'какой-то текст', '']) {
      if (run({ session: sess(), message_text: t }).debug.rotate === true) { rotating.add('text:' + t); }
    }
  }
  eq([...rotating].sort().join(', '), 'NEW_CONFIRM, RESTART_CONFIRM',
    'the set of rotating actions is not the two approved ones');
});

check('a rotate archives a lead only when one exists in the CURRENT cycle', () => {
  // RESTART_CONFIRM on a session with no lead is harmless — it mints a cycle and archives nothing.
  // What must never happen is a rotate that loses a lead without recording it.
  for (const sess of [drafting, fresh]) {
    const r = run({ session: sess(), callback_data: A.RESTART_CONFIRM });
    eq(r.debug.rotate, true, 'the confirmed discard did not rotate');
    assert(!r.session.archived_lead_id, 'it archived a lead that did not exist');
  }
  // A lead belonging to a DIFFERENT cycle does not make this cycle committed, and must not be
  // archived by this cycle's discard.
  const foreign = drafting({ lead_id: 'LEAD-OTHER', lead_cycle_id: 'CY-SOMETHING-ELSE' });
  const r = run({ session: foreign, callback_data: A.RESTART_CONFIRM });
  assert(!r.session.archived_lead_id, 'a foreign-cycle lead was archived by this cycle');
});

// ---------------------------------------------------------------- the Mini App button

check('«Открыть бриф» is a web_app button and the only one', () => {
  const r = run({ session: fresh(), callback_data: A.BRIEF });
  eq(r.debug.state_after, 'TG_OPEN_BRIEF', 'state');
  const rows = r.reply_markup.inline_keyboard;
  const webApps = rows.flat().filter((b) => b.web_app);
  eq(webApps.length, 1, 'web_app button count');
  eq(webApps[0].text, 'Открыть бриф', 'web_app label');
  eq(webApps[0].web_app.url, '__PREMIUM_MINIAPP_URL__', 'the URL must stay a deploy-time placeholder');
});

check('no other screen carries a web_app button', () => {
  const screens = [
    { session: fresh(), message_text: '/start' },
    { session: committed(), message_text: '/start' },
    { session: drafting(), message_text: '/start' },
    { session: committed(), callback_data: A.NEW },
    { session: fresh(), callback_data: A.DESCRIBE }
  ];
  for (const s of screens) {
    const r = run(s);
    const n = (r.reply_markup.inline_keyboard || []).flat().filter((b) => b.web_app).length;
    eq(n, 0, 'a web_app button leaked onto ' + r.debug.state_after);
  }
});

check('every non-web_app button carries a callback in the approved vocabulary', () => {
  const known = Object.keys(A).map((k) => A[k]);
  const screens = [
    { session: fresh(), message_text: '/start' }, { session: committed(), message_text: '/start' },
    { session: drafting(), message_text: '/start' }, { session: committed(), callback_data: A.NEW },
    { session: committed(), callback_data: A.APPEND }, { session: drafting(), callback_data: A.RESTART }
  ];
  for (const s of screens) {
    for (const b of (run(s).reply_markup.inline_keyboard || []).flat()) {
      if (b.web_app) { continue; }
      assert(known.indexOf(b.callback_data) !== -1, 'unknown callback: ' + b.callback_data);
      assert(Buffer.byteLength(b.callback_data, 'utf8') <= 64, 'callback over Telegram 64-byte cap: ' + b.callback_data);
    }
  }
});

// ---------------------------------------------------------------- free text and context

check('free text on the problem screen is captured verbatim and bounded', () => {
  // Where it lands next depends on whether anything was extracted; the two checks below cover both.
  // What must hold either way is that the client's own words are stored and not re-worded.
  const s = drafting({ state: 'TG_FREEFORM_PROBLEM' });
  const r = run({ session: s, message_text: 'У нас три юрлица и сводка собирается вручную.' });
  eq(r.session.free_text_request, 'У нас три юрлица и сводка собирается вручную.', 'the free text was altered or dropped');
  eq(r.debug.writes.indexOf('free_text') !== -1, true, 'the free_text write was not recorded');
});

check('the confirmation screen is built from EXTRACTION, and omits what was not found', () => {
  // The seeded context_extracted_json is no longer the input: extraction now runs in the node and
  // derives the context from the message itself. The fixture is the MESSAGE.
  const r = run({
    session: drafting({ state: 'TG_FREEFORM_PROBLEM' }),
    message_text: 'Я собственник, у нас ООО «Ромашка». Постоянно возникают кассовые разрывы, платежный календарь не ведется.'
  });
  eq(r.debug.state_after, 'TG_CONFIRM_CONTEXT', 'state');
  // Owner decision 1: label and value on separate lines, the value in bold.
  assert(r.reply_text.indexOf('Компания\n<b>Ромашка</b>') !== -1, 'the extracted company is missing: ' + r.reply_text);
  assert(r.reply_text.indexOf('Ваша роль\n<b>Собственник</b>') !== -1, 'the extracted role is missing');
  assert(r.reply_text.indexOf('Задача\n<b>Денежный поток</b>') !== -1, 'the extracted objective is missing');
  // Scale was never asked and is never inferred, so it renders no label at all.
  assert(r.reply_text.indexOf('Масштаб') === -1, 'an uninferred scale rendered a label');
  // An em dash is legitimate inside the approved closing sentence. What must never appear is one
  // standing in for a value that was not extracted.
  assert(!/\n(—|-)\n/.test(r.reply_text) && r.reply_text.indexOf('<b>—</b>') === -1,
    'an em dash placeholder leaked into the confirmation screen');
  eq(labels(r).join(' | '), 'Всё верно | Исправить', 'confirmation actions');
});

check('the extracted context is stored for the Mini App, and never marked confirmed', () => {
  const r = run({
    session: drafting({ state: 'TG_FREEFORM_PROBLEM' }),
    message_text: 'Я собственник, у нас ООО «Ромашка». Постоянные кассовые разрывы и нехватка денег.'
  });
  const ctx = JSON.parse(r.session.context_extracted_json);
  eq(ctx.company_name, 'Ромашка', 'stored company');
  eq(r.session.context_confirmed, 'false', 'extraction marked itself confirmed');
});

check('with no STRUCTURE found, the confirm screen is skipped rather than echoing the client', () => {
  // Extraction always produces a problem summary from any non-empty text. A screen headed
  // «Проверьте, правильно ли FINMENTOR понял ваш контекст» that shows only the client's own
  // sentence back to them is a step with no decision in it.
  const r = run({ session: drafting({ state: 'TG_FREEFORM_PROBLEM' }), message_text: 'Хочу обсудить найм персонала.' });
  eq(r.debug.state_after, 'TG_OPEN_BRIEF', 'state');
  assert(r.reply_text.indexOf('Проверьте') === -1, 'an empty confirmation screen was rendered');
  assert(/найм персонала/.test(r.session.free_text_request), 'the free text was dropped');
});

check('«Исправить» clears the stored guess so nothing later prefills from it', () => {
  const seeded = drafting({
    state: 'TG_CONFIRM_CONTEXT',
    context_extracted_json: JSON.stringify({ company_name: 'Ромашка', objective: 'Денежный поток' })
  });
  const r = run({ session: seeded, callback_data: A.CONFIRM_FIX });
  eq(r.debug.state_after, 'TG_FREEFORM_PROBLEM', 'state');
  eq(r.session.context_extracted_json, '', 'the rejected guess was kept');
  eq(r.session.context_confirmed, 'false', 'confirmed flag survived a correction');
});

check('an objective outside the approved taxonomy never reaches the screen', () => {
  const r = run({
    session: drafting({ state: 'TG_FREEFORM_PROBLEM' }),
    message_text: 'Я собственник. Нужно оптимизировать налоги и наладить работу с юристами.'
  });
  // Role is found, so the screen renders. The client's own words legitimately appear under
  // «Основная ситуация» — that is their summary, not a claim by the product. What must NOT appear
  // is a «Задача:» line, because no approved objective was established.
  assert(r.reply_text.indexOf('Задача:') === -1, 'an objective was shown without one being established');
  for (const label of ['Финансовое управление', 'Денежный поток', 'Прибыль и эффективность',
                       'Нужен независимый взгляд', 'Другая задача']) {
    assert(r.reply_text.indexOf(label) === -1, 'an objective label was invented: ' + label);
  }
  const ctx = JSON.parse(r.session.context_extracted_json || '{}');
  eq(String(ctx.objective || ''), '', 'an off-taxonomy objective was stored');
});

check('«Всё верно» is the only promotion of extracted context, and it opens the brief', () => {
  const s = drafting({ state: 'TG_CONFIRM_CONTEXT' });
  const r = run({ session: s, callback_data: A.CONFIRM_OK });
  eq(r.debug.state_after, 'TG_OPEN_BRIEF', 'state');
  eq(r.session.context_confirmed, 'true', 'context was not marked confirmed');
});

check('appending to a committed request does not create a new one', () => {
  const s = committed({ state: 'TG_APPEND_MESSAGE' });
  const r = run({ session: s, message_text: 'Забыл добавить: сроки до конца квартала.' });
  eq(r.debug.rotate, false, 'an append rotated the cycle');
  eq(r.session.lead_id, LEAD, 'an append destroyed the lead');
  assert(/сроки до конца квартала/.test(r.session.append_text), 'the appended text was not stored');
});

// ---------------------------------------------------------------- what it must never do

check('the premium node never marks a lead ready — submission belongs to /miniapp/submit', () => {
  const screens = [
    { session: fresh(), message_text: '/start' }, { session: fresh(), callback_data: A.BRIEF },
    { session: drafting(), callback_data: A.RESUME }, { session: committed(), callback_data: A.NEW_CONFIRM },
    { session: drafting({ state: 'TG_FREEFORM_PROBLEM' }), message_text: 'текст' }
  ];
  for (const s of screens) {
    const r = run(s);
    eq(r.lead_ready, false, 'lead_ready set on ' + r.debug.state_after);
    eq(r.lead_payload, null, 'lead_payload built on ' + r.debug.state_after);
  }
});

check('an unknown state in the stored session cannot wedge the bot', () => {
  const r = run({ session: fresh({ state: 'GARBAGE_STATE' }), message_text: 'привет' });
  assert(r.debug.state_after.indexOf('TG_') === 0, 'landed on a non-premium state: ' + r.debug.state_after);
  assert(r.reply_text.length > 0, 'the bot answered with nothing');
});

check('a missing session does not throw', () => {
  const r = run({ chat_id: CHAT, message_text: '/start' });
  eq(r.debug.state_after, 'TG_ENTRY', 'state');
  assert(r.reply_text.length > 0, 'empty reply');
});

check('the reply is Telegram-safe and within the length cap', () => {
  const long = 'а'.repeat(9000);
  const r = run({ session: drafting({ state: 'TG_FREEFORM_PROBLEM' }), message_text: long });
  assert(r.reply_text.length <= 3803, 'reply exceeds the cap: ' + r.reply_text.length);
  assert(r.session.free_text_request.length <= 500, 'stored free text exceeds 500 chars');

  // The screen is HTML now, so "no angle brackets at all" is no longer the safety property —
  // the authored copy needs its tags. The property is that NO angle bracket in the reply came
  // from the client: every raw tag must be one the copy wrote, and the client's are escaped.
  const hostile = run({ session: drafting({ state: 'TG_FREEFORM_PROBLEM' }),
    message_text: 'Я собственник ООО «Ромашка». <b>Кассовые разрывы</b> & нет платежного календаря.' });
  assert(hostile.reply_text.indexOf('&lt;b&gt;') !== -1, 'a client-supplied tag was not escaped');
  assert(hostile.reply_text.indexOf('&amp;') !== -1, 'a client-supplied ampersand was not escaped');
  for (const m of hostile.reply_text.matchAll(/<\/?([a-z-]+)[^>]*>/g)) {
    assert(['b', 'i'].indexOf(m[1]) !== -1, 'an unexpected raw tag reached the reply: ' + m[1]);
  }
});

// ---------------------------------------------------------------- the candidate as an artifact

check('the candidate carries no production identifier and no live URL', () => {
  const json = JSON.stringify(wf);
  for (const leak of ['cachedResultUrl', 'cachedResultName', 'activeVersion', 'versionId', 'pinData']) {
    assert(json.indexOf('"' + leak + '"') === -1, 'leaked key: ' + leak);
  }
  assert(json.indexOf('t.me/') === -1, 'a Telegram link is baked in');
  assert(/^\[CANDIDATE\]/.test(wf.name), 'the candidate is not named as one: ' + wf.name);
});

check('the P9-R2 flag pair is absent from every node', () => {
  for (const n of wf.nodes) {
    assert(!(n.alwaysOutputData === true && n.onError === 'continueErrorOutput'),
      'P9-R2 flag pair on ' + n.name);
  }
  eq(wf.nodes.length, 51, 'node count');
});

// ---------------------------------------------------------------- the customer conversation

check('the conversation is SPLICED — no node added, none removed, no edge moved', () => {
  // P1-01. The premium conversation used to be three ADDED nodes behind an owner gate. It is now
  // the two live nodes themselves, because thirteen downstream nodes read `$('Build Bot Response')`
  // and thirteen read `$('Get Bot Session')` BY NAME: a customer sent down a parallel branch would
  // reach a node whose `$('Build Bot Response')` never ran.
  const live = JSON.parse(readFileSync(join(ROOT, 'n8n', 'history', 'mppzthlkSJFr6Kle.pre-premium-ux.json'), 'utf8'));
  const spliced = ['Get Bot Session', 'Build Bot Response'];
  eq(wf.nodes.length, live.nodes.length, 'node count');
  for (const n of wf.nodes) {
    const was = live.nodes.find((x) => x.name === n.name);
    assert(was, 'unexpected new node: ' + n.name);
    if (spliced.indexOf(n.name) !== -1) {
      // The spliced nodes may differ in `parameters.jsCode` and in nothing else.
      const a = JSON.parse(JSON.stringify(n));
      const b = JSON.parse(JSON.stringify(was));
      a.parameters.jsCode = ''; b.parameters.jsCode = '';
      eq(JSON.stringify(a), JSON.stringify(b), n.name + ' changed beyond its node body');
      assert(n.parameters.jsCode !== was.parameters.jsCode, n.name + ': the splice did not change the body');
      continue;
    }
    eq(JSON.stringify(n), JSON.stringify(was), 'a live node was modified: ' + n.name);
  }
  for (const n of live.nodes) {
    assert(wf.nodes.find((x) => x.name === n.name), 'a live node was removed: ' + n.name);
  }
  // The retired owner branch must be gone, not merely bypassed.
  for (const gone of ['Premium Owner Gate', 'Get Bot Session (Premium)', 'Build Bot Response (Premium)']) {
    assert(!wf.nodes.find((x) => x.name === gone), 'the retired owner branch is still present: ' + gone);
  }
});

check('the connection graph is byte-identical to the live workflow', () => {
  const live = JSON.parse(readFileSync(join(ROOT, 'n8n', 'history', 'mppzthlkSJFr6Kle.pre-premium-ux.json'), 'utf8'));
  const keys = [...new Set(Object.keys(live.connections).concat(Object.keys(wf.connections)))].sort();
  for (const k of keys) {
    eq(JSON.stringify(wf.connections[k]), JSON.stringify(live.connections[k]), 'edge changed: ' + k);
  }
  eq(wf.connections['Find Session'].main[0][0].node, 'Get Bot Session', 'the customer path entry');
  eq(wf.connections['Get Bot Session'].main[0][0].node, 'Build Bot Response', 'the customer path');
  eq(wf.connections['Build Bot Response'].main[0][0].node, 'Build Transport Request', 'the rejoin');
});

check('every downstream $(...) reference names a node the candidate still contains', () => {
  // This is the check the retired parallel branch could never have passed.
  const names = new Set(wf.nodes.map((n) => n.name));
  const referenced = new Set();
  for (const n of wf.nodes) {
    const j = JSON.stringify(n.parameters || {});
    for (const m of j.matchAll(/\$\(\\?['"]([^'"\\]+)\\?['"]\)/g)) { referenced.add(m[1]); }
  }
  for (const r of referenced) { assert(names.has(r), 'a node references $("' + r + '"), which is gone'); }
  for (const must of ['Get Bot Session', 'Build Bot Response']) {
    assert(referenced.has(must), 'nothing references $("' + must + '") — the splice went to the wrong node');
  }
});

check('the /start reset is gone for EVERY customer, not just the owner', () => {
  // The reset archived lead_id, cleared consent and wiped every qualification answer. It is a
  // customer-facing data-loss defect, and it matters more now that `/start ro` is the ordinary way
  // a Romanian customer arrives.
  const session = wf.nodes.find((n) => n.name === 'Get Bot Session');
  const code = session.parameters.jsCode;
  const exec = code.split('\n').filter((l) => !/^\s*\/\//.test(l)).join('\n');
  assert(!/if \(isStart\) reset = /.test(exec), 'the /start reset is still executable');
  assert(/\[premium\] REMOVED/.test(code), 'the removal is not recorded in the node');
  for (const keep of ['SUBMISSION_KEY_RE', 'hasNoCycle', 'cycle_reset', '__submission_key_action']) {
    assert(code.indexOf(keep) !== -1, 'the session node lost ' + keep);
  }
});

// ---------------------------------------------------------------- the owner boundary

check('no owner identity decides anything on the customer path', () => {
  // Making the conversation reachable by customers must not hand a customer one byte of owner
  // authority. The Concierge holds no owner control at all — `Hot Path Config` deliberately stops
  // emitting owner_chat_id — and the two spliced nodes must not reintroduce one.
  for (const name of ['Get Bot Session', 'Build Bot Response']) {
    const n = wf.nodes.find((x) => x.name === name);
    const exec = n.parameters.jsCode.split('\n').filter((l) => !/^\s*\/\//.test(l)).join('\n');
    assert(!/owner_chat_id|owner_id|is_owner|isOwner/.test(exec), name + ' reads an owner identity');
    const hits = (exec.match(/\b\d{7,}\b/g) || []);
    eq(hits.length, 0, name + ' embeds a long numeric id: ' + hits.slice(0, 3).join(', '));
  }
});

check('a non-owner customer can only ever be shown the customer callback vocabulary', () => {
  // Every keyboard the conversation can build, across every reachable screen, over both locales.
  const APPROVED = new Set(Object.keys(A).map((k) => A[k]));
  const seen = new Set();
  const sessions = [
    fresh(), fresh({ state: 'TG_FREEFORM_PROBLEM' }), fresh({ state: 'TG_CONFIRM_CONTEXT' }),
    drafting(), drafting({ state: 'TG_RESUME_DRAFT' }), committed(),
    committed({ state: 'TG_APPEND_MESSAGE' }), committed({ state: 'TG_NEW_REQUEST_CONFIRM' })
  ];
  const inputs = [{ message_text: '/start' }, { message_text: '/start ro' }, { message_text: 'текст' }]
    .concat(Object.keys(A).map((k) => ({ callback_data: A[k] })));
  for (const language of ['ru', 'ro', 'ro-MD', 'en', '']) {
    for (const s of sessions) {
      for (const i of inputs) {
        const r = run(Object.assign({ session: Object.assign({}, s, { language: language }) }, i));
        for (const row of r.reply_markup.inline_keyboard || []) {
          for (const btn of row) {
            if (btn.web_app) { continue; }
            seen.add(btn.callback_data);
          }
        }
      }
    }
  }
  assert(seen.size > 0, 'no keyboard was produced at all — the sweep proved nothing');
  for (const cb of seen) {
    assert(APPROVED.has(cb), 'a callback outside the customer vocabulary reached a customer: ' + cb);
  }
  // The owner surfaces use their own prefixes. None may appear anywhere in the customer node.
  const body2 = wf.nodes.find((n) => n.name === 'Build Bot Response').parameters.jsCode;
  for (const owner of ['lead|', 'stage|', 'crm|', 'ack|', 'close|', 'won|', 'lost|', 'nurture|', 'admin|', 'owner|']) {
    assert(body2.indexOf('"' + owner) === -1 && body2.indexOf("'" + owner) === -1,
      'an owner callback prefix is present in the customer node: ' + owner);
  }
});

check('the set of workflows the Concierge calls is unchanged', () => {
  // The transport and the internal Lead Intake handoff, both of which already existed and neither
  // of which is an owner control. A new executeWorkflow call would be a new authority.
  const live = JSON.parse(readFileSync(join(ROOT, 'n8n', 'history', 'mppzthlkSJFr6Kle.pre-premium-ux.json'), 'utf8'));
  const now = wf.nodes.filter((n) => n.type === 'n8n-nodes-base.executeWorkflow').map((n) => n.name).sort();
  const was = live.nodes.filter((n) => n.type === 'n8n-nodes-base.executeWorkflow').map((n) => n.name).sort();
  eq(now.join(','), was.join(','), 'the set of called workflows changed');
});

check('the two spliced nodes embed no Telegram id', () => {
  // Scoped to what this delta introduced. The rest of the artifact is the live workflow verbatim,
  // and the long numbers in it are spreadsheet gids and timestamps that were already there.
  for (const name of ['Get Bot Session', 'Build Bot Response']) {
    const n = wf.nodes.find((x) => x.name === name);
    const hits = (JSON.stringify(n).match(/\b\d{7,}\b/g) || []);
    eq(hits.length, 0, name + ' embeds a long numeric id: ' + hits.slice(0, 3).join(', '));
  }
});

check('an empty message stays on the free-text screen and stores nothing', () => {
  // Live defect, RU owner UAT: an empty message is still a text input, so decide() answered
  // TG_CONFIRM_CONTEXT with an empty free_text, extraction found nothing (correctly), and the
  // 'a confirmation screen with nothing on it is worse than none' rule forwarded to TG_OPEN_BRIEF
  // — walking the client PAST the only question the screen asks.
  const BLANKS = ['', '   ', String.fromCharCode(10, 10), String.fromCharCode(9)];
  for (const text of BLANKS) {
    const r = run({ session: fresh({ state: 'TG_FREEFORM_PROBLEM' }), message_text: text });
    eq(r.debug.state_after, 'TG_FREEFORM_PROBLEM', 'empty text ' + JSON.stringify(text) + ' left the screen');
    eq(String(r.session.free_text_request || ''), '', 'an empty summary was stored');
    eq(String(r.session.context_confirmed || 'false'), 'false', 'something was marked confirmed');
  }
});

check('a real message still leaves the free-text screen', () => {
  // The guard must be narrow: it may only catch the empty case.
  const r = run({ session: fresh({ state: 'TG_FREEFORM_PROBLEM' }),
    message_text: 'Я собственник, кассовые разрывы, нужен прогноз движения денежных средств.' });
  assert(r.debug.state_after !== 'TG_FREEFORM_PROBLEM', 'a real message was swallowed by the empty guard');
  assert(String(r.session.free_text_request || '').length > 0, 'the real text was not stored');
});

console.log('');
if (failures.length) {
  console.log('FAILURES (' + failures.length + '):');
  failures.forEach((f) => console.log('  - ' + f));
  console.log('');
  console.log('ASSERTIONS: ' + pass + ' passed, ' + failures.length + ' failed');
  process.exit(1);
}
console.log('ASSERTIONS: ' + pass + ' passed');
