#!/usr/bin/env node
// FINMENTOR — the Premium Concierge candidate, EXECUTED.
//
//   node qa/premium-ux-concierge-candidate.test.mjs
//
// Offline. No tenant, no network, no credentials.
//
// WHY THIS GATE RUNS THE NODE INSTEAD OF READING IT. The candidate's node body is generated by
// scripts/build-premium-concierge.mjs, and that script's own checks are string matches: they can
// tell you the word `rotate` appears twice, not that a committed cycle survives a `/start`. A
// generated artifact that has never been executed is a guess with good punctuation.
//
// So this loads the candidate JSON, lifts `Build Bot Response` out of it, and runs it against a
// stub `$input` for each scenario that matters — including the ones that must NOT happen.

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const CANDIDATE = join(ROOT, 'n8n', 'candidate', 'premium-concierge-candidate.json');

let pass = 0;
const failures = [];
function check(name, fn) {
  try { fn(); pass++; console.log('  PASS  ' + name); }
  catch (e) { failures.push(name + ': ' + e.message); console.log('  FAIL  ' + name + ' -> ' + e.message); }
}
const assert = (c, m) => { if (!c) throw new Error(m); };
const eq = (a, b, m) => { if (a !== b) throw new Error(m + ' (got ' + JSON.stringify(a) + ', want ' + JSON.stringify(b) + ')'); };

const wf = JSON.parse(readFileSync(CANDIDATE, 'utf8'));
const body = wf.nodes.find((n) => n.name === 'Build Bot Response').parameters.jsCode;

// The node reads `$input.first().json`. Everything else it touches is its own.
const runner = new Function('$input', body);
function run(src) { return runner({ first: () => ({ json: src }) })[0].json; }

const CHAT = '777000';
const CYCLE = 'CY-2026-08-29-abcdef';
const LEAD = 'LEAD-000123';

// A committed cycle: a lead exists AND belongs to this cycle.
const committed = (extra) => Object.assign({
  chat_id: CHAT, cycle_id: CYCLE, lead_id: LEAD, lead_cycle_id: CYCLE, state: 'TG_SUBMITTED'
}, extra || {});
// An unfinished draft: no lead, draft_state === 'draft'.
const drafting = (extra) => Object.assign({
  chat_id: CHAT, cycle_id: CYCLE, lead_id: '', lead_cycle_id: '', draft_state: 'draft',
  draft_step: 'objective', state: 'TG_ENTRY'
}, extra || {});
const fresh = (extra) => Object.assign({ chat_id: CHAT, cycle_id: CYCLE, state: 'TG_ENTRY' }, extra || {});

const A = {
  DESCRIBE: 'p|describe', BRIEF: 'p|brief', CONFIRM_OK: 'p|ctx_ok', CONFIRM_FIX: 'p|ctx_fix',
  OPEN: 'p|open', RESUME: 'p|resume', RESTART: 'p|restart', RESTART_CONFIRM: 'p|restart_y',
  APPEND: 'p|append', NEW: 'p|new', NEW_CONFIRM: 'p|new_y', BACK: 'p|back', RETRY: 'p|retry'
};

const QUALIFICATION = ['TG_ENTRY', 'TG_FREEFORM_PROBLEM', 'TG_CONFIRM_CONTEXT', 'TG_OPEN_BRIEF', 'TG_RESUME_DRAFT'];
const labels = (r) => (r.reply_markup.inline_keyboard || []).map((row) => row[0].text);

console.log('Premium Concierge candidate — executed');
console.log('');

// ---------------------------------------------------------------- it runs at all

check('the generated node executes and returns the full output contract', () => {
  const r = run({ session: fresh(), message_text: '/start' });
  for (const k of ['chat_id', 'reply_text', 'reply_markup', 'tg_body', 'session',
                   'lead_ready', 'lead_payload', 'ai_guarded', 'debug', 'event']) {
    assert(Object.prototype.hasOwnProperty.call(r, k), 'missing output key: ' + k);
  }
  eq(r.chat_id, CHAT, 'chat_id');
  eq(r.tg_body.chat_id, CHAT, 'tg_body.chat_id');
  eq(r.tg_body.text, r.reply_text, 'tg_body.text must equal reply_text');
});

// ---------------------------------------------------------------- the three-way /start

check('/start on a fresh session shows the entry screen', () => {
  const r = run({ session: fresh(), message_text: '/start' });
  eq(r.debug.state_after, 'TG_ENTRY', 'state');
  eq(labels(r).join(' | '), 'Описать задачу | Подготовить бриф', 'entry actions');
});

check('/start on an unfinished draft offers RESUME, not a fresh start', () => {
  const r = run({ session: drafting(), message_text: '/start' });
  eq(r.debug.state_after, 'TG_RESUME_DRAFT', 'state');
  eq(r.debug.rotate, false, 'a resume must not rotate');
  assert(/Продолжить/.test(r.reply_text) || labels(r).indexOf('Продолжить') !== -1,
    'the resume screen does not offer «Продолжить»');
});

check('/start on a COMMITTED cycle lands on the terminal screen — the defect this replaces', () => {
  const r = run({ session: committed(), message_text: '/start' });
  eq(r.debug.state_after, 'TG_SUBMITTED', 'state');
  eq(r.debug.rotate, false, 'the /start reset rotated a committed cycle');
  eq(r.session.lead_id, LEAD, 'the committed lead_id was destroyed by /start');
  eq(r.session.cycle_id, CYCLE, 'the cycle was rotated by /start');
});

check('/menu behaves exactly like /start', () => {
  const a = run({ session: committed(), message_text: '/menu' });
  eq(a.debug.state_after, 'TG_SUBMITTED', '/menu on committed');
  const b = run({ session: fresh(), message_text: '/menu' });
  eq(b.debug.state_after, 'TG_ENTRY', '/menu on fresh');
});

// ---------------------------------------------------------------- the terminal rule

check('NO input returns a committed cycle to qualification', () => {
  const inputs = [
    { message_text: '/start' }, { message_text: '/menu' }, { message_text: 'здравствуйте' },
    { message_text: 'хочу новый бриф' },
    ...Object.keys(A).filter((k) => k !== 'NEW_CONFIRM').map((k) => ({ callback_data: A[k] }))
  ];
  for (const i of inputs) {
    const r = run(Object.assign({ session: committed() }, i));
    assert(QUALIFICATION.indexOf(r.debug.state_after) === -1,
      'input ' + JSON.stringify(i) + ' reached qualification state ' + r.debug.state_after);
    eq(r.session.lead_id, LEAD, 'input ' + JSON.stringify(i) + ' destroyed the committed lead');
    eq(r.debug.rotate, false, 'input ' + JSON.stringify(i) + ' rotated the cycle');
  }
});

check('a stale inline button from an old message cannot rotate a committed cycle', () => {
  // The button that used to advance a draft, tapped after submission.
  for (const stale of [A.OPEN, A.RESUME, A.CONFIRM_OK, A.DESCRIBE, A.BRIEF, A.RESTART_CONFIRM]) {
    const r = run({ session: committed(), callback_data: stale });
    eq(r.debug.state_after, 'TG_SUBMITTED', 'stale ' + stale);
    eq(r.session.lead_id, LEAD, 'stale ' + stale + ' destroyed the lead');
  }
});

check('«Начать новый вопрос» asks first and rotates nothing', () => {
  const r = run({ session: committed(), callback_data: A.NEW });
  eq(r.debug.state_after, 'TG_NEW_REQUEST_CONFIRM', 'state');
  eq(r.debug.rotate, false, 'the unconfirmed tap rotated');
  eq(r.session.lead_id, LEAD, 'the unconfirmed tap destroyed the lead');
});

check('only the CONFIRMED new-request rotates, and it archives the lead', () => {
  const r = run({ session: committed(), callback_data: A.NEW_CONFIRM });
  eq(r.debug.rotate, true, 'the confirmed action did not rotate');
  eq(r.debug.state_after, 'TG_ENTRY', 'state after rotate');
  eq(r.session.archived_lead_id, LEAD, 'the lead was not archived — it was simply lost');
  eq(r.session.lead_id, '', 'lead_id was not cleared');
  eq(r.session.cycle_id, '', 'the new cycle must be minted by the issuer, not here');
});

check('a confirmed DISCARD of an uncommitted draft rotates but archives nothing', () => {
  const r = run({ session: drafting(), callback_data: A.RESTART_CONFIRM });
  eq(r.debug.rotate, true, 'the confirmed discard did not rotate');
  assert(!r.session.archived_lead_id, 'it archived a lead that never existed');
  eq(r.session.draft_state, '', 'the draft was not cleared');
});

check('«Начать заново» on a draft asks first', () => {
  const r = run({ session: drafting(), callback_data: A.RESTART });
  eq(r.debug.rotate, false, 'the unconfirmed discard rotated');
  eq(r.debug.state_after, 'TG_NEW_REQUEST_CONFIRM', 'state');
});

check('exactly two ACTIONS in the whole vocabulary can rotate a cycle', () => {
  // The invariant is about BRANCHES, not about state-input pairs. RESTART_CONFIRM reaches the same
  // single branch from a draft and from a session that has neither draft nor lead; counting those
  // as two findings measures the fixture, not the machine.
  const rotating = new Set();
  for (const sess of [committed, drafting, fresh]) {
    for (const k of Object.keys(A)) {
      if (run({ session: sess(), callback_data: A[k] }).debug.rotate === true) { rotating.add(k); }
    }
    for (const t of ['/start', '/menu', 'какой-то текст', '']) {
      if (run({ session: sess(), message_text: t }).debug.rotate === true) { rotating.add('text:' + t); }
    }
  }
  eq([...rotating].sort().join(', '), 'NEW_CONFIRM, RESTART_CONFIRM',
    'the set of rotating actions is not the two approved ones');
});

check('a rotate archives a lead only when one exists in the CURRENT cycle', () => {
  // RESTART_CONFIRM on a session with no lead is harmless — it mints a cycle and archives nothing.
  // What must never happen is a rotate that loses a lead without recording it.
  for (const sess of [drafting, fresh]) {
    const r = run({ session: sess(), callback_data: A.RESTART_CONFIRM });
    eq(r.debug.rotate, true, 'the confirmed discard did not rotate');
    assert(!r.session.archived_lead_id, 'it archived a lead that did not exist');
  }
  // A lead belonging to a DIFFERENT cycle does not make this cycle committed, and must not be
  // archived by this cycle's discard.
  const foreign = drafting({ lead_id: 'LEAD-OTHER', lead_cycle_id: 'CY-SOMETHING-ELSE' });
  const r = run({ session: foreign, callback_data: A.RESTART_CONFIRM });
  assert(!r.session.archived_lead_id, 'a foreign-cycle lead was archived by this cycle');
});

// ---------------------------------------------------------------- the Mini App button

check('«Открыть бриф» is a web_app button and the only one', () => {
  const r = run({ session: fresh(), callback_data: A.BRIEF });
  eq(r.debug.state_after, 'TG_OPEN_BRIEF', 'state');
  const rows = r.reply_markup.inline_keyboard;
  const webApps = rows.flat().filter((b) => b.web_app);
  eq(webApps.length, 1, 'web_app button count');
  eq(webApps[0].text, 'Открыть бриф', 'web_app label');
  eq(webApps[0].web_app.url, '__PREMIUM_MINIAPP_URL__', 'the URL must stay a deploy-time placeholder');
});

check('no other screen carries a web_app button', () => {
  const screens = [
    { session: fresh(), message_text: '/start' },
    { session: committed(), message_text: '/start' },
    { session: drafting(), message_text: '/start' },
    { session: committed(), callback_data: A.NEW },
    { session: fresh(), callback_data: A.DESCRIBE }
  ];
  for (const s of screens) {
    const r = run(s);
    const n = (r.reply_markup.inline_keyboard || []).flat().filter((b) => b.web_app).length;
    eq(n, 0, 'a web_app button leaked onto ' + r.debug.state_after);
  }
});

check('every non-web_app button carries a callback in the approved vocabulary', () => {
  const known = Object.keys(A).map((k) => A[k]);
  const screens = [
    { session: fresh(), message_text: '/start' }, { session: committed(), message_text: '/start' },
    { session: drafting(), message_text: '/start' }, { session: committed(), callback_data: A.NEW },
    { session: committed(), callback_data: A.APPEND }, { session: drafting(), callback_data: A.RESTART }
  ];
  for (const s of screens) {
    for (const b of (run(s).reply_markup.inline_keyboard || []).flat()) {
      if (b.web_app) { continue; }
      assert(known.indexOf(b.callback_data) !== -1, 'unknown callback: ' + b.callback_data);
      assert(Buffer.byteLength(b.callback_data, 'utf8') <= 64, 'callback over Telegram 64-byte cap: ' + b.callback_data);
    }
  }
});

// ---------------------------------------------------------------- free text and context

check('free text on the problem screen is captured verbatim and bounded', () => {
  // Where it lands next depends on whether anything was extracted; the two checks below cover both.
  // What must hold either way is that the client's own words are stored and not re-worded.
  const s = drafting({ state: 'TG_FREEFORM_PROBLEM' });
  const r = run({ session: s, message_text: 'У нас три юрлица и сводка собирается вручную.' });
  eq(r.session.free_text_request, 'У нас три юрлица и сводка собирается вручную.', 'the free text was altered or dropped');
  eq(r.debug.writes.indexOf('free_text') !== -1, true, 'the free_text write was not recorded');
});

check('the confirmation screen is built from EXTRACTION, and omits what was not found', () => {
  // The seeded context_extracted_json is no longer the input: extraction now runs in the node and
  // derives the context from the message itself. The fixture is the MESSAGE.
  const r = run({
    session: drafting({ state: 'TG_FREEFORM_PROBLEM' }),
    message_text: 'Я собственник, у нас ООО «Ромашка». Постоянно возникают кассовые разрывы, платежный календарь не ведется.'
  });
  eq(r.debug.state_after, 'TG_CONFIRM_CONTEXT', 'state');
  assert(r.reply_text.indexOf('Компания: Ромашка') !== -1, 'the extracted company is missing: ' + r.reply_text);
  assert(r.reply_text.indexOf('Ваша роль: Собственник') !== -1, 'the extracted role is missing');
  assert(r.reply_text.indexOf('Задача: Денежный поток') !== -1, 'the extracted objective is missing');
  // Scale was never asked and is never inferred, so it renders no label at all.
  assert(r.reply_text.indexOf('Масштаб') === -1, 'an uninferred scale rendered a label');
  assert(r.reply_text.indexOf('—') === -1, 'an em dash placeholder leaked into the confirmation screen');
  eq(labels(r).join(' | '), 'Всё верно | Исправить', 'confirmation actions');
});

check('the extracted context is stored for the Mini App, and never marked confirmed', () => {
  const r = run({
    session: drafting({ state: 'TG_FREEFORM_PROBLEM' }),
    message_text: 'Я собственник, у нас ООО «Ромашка». Постоянные кассовые разрывы и нехватка денег.'
  });
  const ctx = JSON.parse(r.session.context_extracted_json);
  eq(ctx.company_name, 'Ромашка', 'stored company');
  eq(r.session.context_confirmed, 'false', 'extraction marked itself confirmed');
});

check('with no STRUCTURE found, the confirm screen is skipped rather than echoing the client', () => {
  // Extraction always produces a problem summary from any non-empty text. A screen headed
  // «Проверьте, правильно ли FINMENTOR понял ваш контекст» that shows only the client's own
  // sentence back to them is a step with no decision in it.
  const r = run({ session: drafting({ state: 'TG_FREEFORM_PROBLEM' }), message_text: 'Хочу обсудить найм персонала.' });
  eq(r.debug.state_after, 'TG_OPEN_BRIEF', 'state');
  assert(r.reply_text.indexOf('Проверьте') === -1, 'an empty confirmation screen was rendered');
  assert(/найм персонала/.test(r.session.free_text_request), 'the free text was dropped');
});

check('«Исправить» clears the stored guess so nothing later prefills from it', () => {
  const seeded = drafting({
    state: 'TG_CONFIRM_CONTEXT',
    context_extracted_json: JSON.stringify({ company_name: 'Ромашка', objective: 'Денежный поток' })
  });
  const r = run({ session: seeded, callback_data: A.CONFIRM_FIX });
  eq(r.debug.state_after, 'TG_FREEFORM_PROBLEM', 'state');
  eq(r.session.context_extracted_json, '', 'the rejected guess was kept');
  eq(r.session.context_confirmed, 'false', 'confirmed flag survived a correction');
});

check('an objective outside the approved taxonomy never reaches the screen', () => {
  const r = run({
    session: drafting({ state: 'TG_FREEFORM_PROBLEM' }),
    message_text: 'Я собственник. Нужно оптимизировать налоги и наладить работу с юристами.'
  });
  // Role is found, so the screen renders. The client's own words legitimately appear under
  // «Основная ситуация» — that is their summary, not a claim by the product. What must NOT appear
  // is a «Задача:» line, because no approved objective was established.
  assert(r.reply_text.indexOf('Задача:') === -1, 'an objective was shown without one being established');
  for (const label of ['Финансовое управление', 'Денежный поток', 'Прибыль и эффективность',
                       'Нужен независимый взгляд', 'Другая задача']) {
    assert(r.reply_text.indexOf(label) === -1, 'an objective label was invented: ' + label);
  }
  const ctx = JSON.parse(r.session.context_extracted_json || '{}');
  eq(String(ctx.objective || ''), '', 'an off-taxonomy objective was stored');
});

check('«Всё верно» is the only promotion of extracted context, and it opens the brief', () => {
  const s = drafting({ state: 'TG_CONFIRM_CONTEXT' });
  const r = run({ session: s, callback_data: A.CONFIRM_OK });
  eq(r.debug.state_after, 'TG_OPEN_BRIEF', 'state');
  eq(r.session.context_confirmed, 'true', 'context was not marked confirmed');
});

check('appending to a committed request does not create a new one', () => {
  const s = committed({ state: 'TG_APPEND_MESSAGE' });
  const r = run({ session: s, message_text: 'Забыл добавить: сроки до конца квартала.' });
  eq(r.debug.rotate, false, 'an append rotated the cycle');
  eq(r.session.lead_id, LEAD, 'an append destroyed the lead');
  assert(/сроки до конца квартала/.test(r.session.append_text), 'the appended text was not stored');
});

// ---------------------------------------------------------------- what it must never do

check('the premium node never marks a lead ready — submission belongs to /miniapp/submit', () => {
  const screens = [
    { session: fresh(), message_text: '/start' }, { session: fresh(), callback_data: A.BRIEF },
    { session: drafting(), callback_data: A.RESUME }, { session: committed(), callback_data: A.NEW_CONFIRM },
    { session: drafting({ state: 'TG_FREEFORM_PROBLEM' }), message_text: 'текст' }
  ];
  for (const s of screens) {
    const r = run(s);
    eq(r.lead_ready, false, 'lead_ready set on ' + r.debug.state_after);
    eq(r.lead_payload, null, 'lead_payload built on ' + r.debug.state_after);
  }
});

check('an unknown state in the stored session cannot wedge the bot', () => {
  const r = run({ session: fresh({ state: 'GARBAGE_STATE' }), message_text: 'привет' });
  assert(r.debug.state_after.indexOf('TG_') === 0, 'landed on a non-premium state: ' + r.debug.state_after);
  assert(r.reply_text.length > 0, 'the bot answered with nothing');
});

check('a missing session does not throw', () => {
  const r = run({ chat_id: CHAT, message_text: '/start' });
  eq(r.debug.state_after, 'TG_ENTRY', 'state');
  assert(r.reply_text.length > 0, 'empty reply');
});

check('the reply is Telegram-safe and within the length cap', () => {
  const long = 'а'.repeat(9000);
  const r = run({ session: drafting({ state: 'TG_FREEFORM_PROBLEM' }), message_text: long });
  assert(r.reply_text.length <= 3803, 'reply exceeds the cap: ' + r.reply_text.length);
  assert(!/[<>]/.test(r.reply_text), 'angle brackets survived into the reply');
  assert(r.session.free_text_request.length <= 500, 'stored free text exceeds 500 chars');
});

// ---------------------------------------------------------------- the candidate as an artifact

check('the candidate carries no production identifier and no live URL', () => {
  const json = JSON.stringify(wf);
  for (const leak of ['cachedResultUrl', 'cachedResultName', 'activeVersion', 'versionId', 'pinData']) {
    assert(json.indexOf('"' + leak + '"') === -1, 'leaked key: ' + leak);
  }
  assert(json.indexOf('t.me/') === -1, 'a Telegram link is baked in');
  assert(/^\[CANDIDATE\]/.test(wf.name), 'the candidate is not named as one: ' + wf.name);
});

check('the P9-R2 flag pair is absent from every node', () => {
  for (const n of wf.nodes) {
    assert(!(n.alwaysOutputData === true && n.onError === 'continueErrorOutput'),
      'P9-R2 flag pair on ' + n.name);
  }
  eq(wf.nodes.length, 51, 'node count');
});

console.log('');
if (failures.length) {
  console.log('FAILURES (' + failures.length + '):');
  failures.forEach((f) => console.log('  - ' + f));
  console.log('');
  console.log('ASSERTIONS: ' + pass + ' passed, ' + failures.length + ' failed');
  process.exit(1);
}
console.log('ASSERTIONS: ' + pass + ' passed');
